{
  "hash": "09ef415eaf7d07c2fcbe175178ccc919",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"MODELOS CONTINUOS Y TLC\"\nsubtitle: \"SHINYS INTERACTIVOS\"\nauthor: \n  - name: Mauricio Borda<br>Johan Rodriguez<br>Alannis Duque\n    affiliation: \"Universidad del Tolima\"\n    affiliation-url: \"https://www.ut.edu.co/\"\ndate: today\nlang: es\nbibliography: referencias.bib\nlink-citations: true\nnocite: |\n  @*\ntitle-block-banner: \"#5f17a3\"\nfilters:\n  - shinylive\nformat:\n  html:\n    page-layout: full\n    fontsize: 14pt\n    toc: true\n    toc-location: right\n\n    number-sections: true\n    code-fold: true\n    code-summary: \"Ver código\"\n    theme: dark\n    highlight-style: monokai\n    html-math-method: katex\n    smooth-scroll: true\n    link-external-newwindow: true\n    code-overflow: scroll\n    favicon: favicon.ico\neditor: visual\n\nknitr:\n  opts_chunk:\n    message: false\n    warning: false\n    fig.align: center\n    fig.width: 6\n    fig.height: 6\n    out.width: \"70%\"\n---\n\n```{=html}\n<div style=\"position:absolute; top:10px; right:10px;\">\n<img src=\"ut.png\" width=\"150\">\n</div>\n```\n\n```{=html}\n<style>\nbody{\n  background-color:#ffffff;\n  font-size:130%;\n  text-align:justify;\n}\n</style>\n```\n\n# Cargar paquetes\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nipak <- function(pkg){\n\n  options(repos = c(CRAN=\"https://cloud.r-project.org\"))\n\n  new.pkg <- pkg[!(pkg %in% rownames(installed.packages()))]\n\n  if(length(new.pkg)) install.packages(new.pkg, dependencies = TRUE)\n\n  invisible(lapply(pkg, function(p)\n    suppressPackageStartupMessages(library(p, character.only = TRUE))\n  ))\n}\n\npackages <- c(\"tidyverse\",\"kableExtra\",\"psych\",\"readxl\")\n\nipak(packages)\n```\n:::\n\n\n# Distribucion Normal\n\nLa distribución normal, también conocida como distribución gaussiana o campana de Gauss, es la distribución de probabilidad continua más importante en la estadística.\n\nSu importancia radica en que muchos fenómenos naturales, sociales y económicos siguen este patrón.\n\nLa distribución normal es la distribución de probabilidad continua más usada en estadística y una herramienta fundamental para modelar una inmensa variedad de fenómenos en las ciencias, la ingeniería y la economía. Su popularidad se debe a una propiedad matemática conocida como el Teorema del Límite Central, que establece que la suma o el promedio de un gran número de variables aleatorias independientes (sin importar su distribución original) tiende a seguir una distribución normal.\n\nCaracterísticas Clave\n\nLa distribución normal es un tipo de distribución de probabilidad continua. Esto significa que la variable aleatoria puede tomar cualquier valor dentro de un rango determinado. Se representa por una curva simétrica en forma de campana, donde la mayor parte de los datos se agrupan alrededor del valor central.\n\n**Forma de Campana:** La distribución es simétrica alrededor de su media, creando una curva con forma de campana. El punto más alto de la campana es la media.\n\n**Media, Mediana y Moda Coincidentes:** En una distribución normal perfecta, estos tres valores son iguales y se encuentran en el centro de la curva.\n\n**Asintótica al Eje Horizontal:** La curva se extiende indefinidamente en ambas direcciones, acercándose al eje x pero sin llegar a tocarlo.\n\n**Regla Empírica:** Alrededor del 68% de los datos se encuentran dentro de una desviación estándar de la media (μ±σ), el 95% dentro de dos desviaciones estándar (μ±2σ), y el 99.7% dentro de tres desviaciones estándar (μ±3σ).\n\n- **Parámetros**\n\nLa distribución normal está completamente definida por dos parámetros:\n\n**Media (μ):** Indica la ubicación del centro de la curva y el valor más probable.\n\n**Varianza σ2σ2 o Desviación Estándar (σ):** Mide la dispersión o variabilidad de los datos. Una σ grande resulta en una curva más ancha y aplanada, mientras que una σ pequeña crea una curva más estrecha y alta.\n\n- **Fórmulas**\n\nLa fórmula principal de la distribución normal es la función de densidad de probabilidad (FDP). Esta función no calcula la probabilidad de un punto exacto, sino la densidad de probabilidad en ese punto.\n\nFunción de Densidad de Probabilidad (FDP):\n\n$$f(x)=σ2π\n​1​e−21​(σx−μ​)2$$\n\nDonde:\n\n**x** es el valor de la variable aleatoria.\n\n**μ** es la media.\n\n**σ** es la desviación estándar.\n\n**e** es el número de Euler (aproximadamente 2.71828).\n\n**π** es la constante pi (aproximadamente 3.14159).\n\nPara calcular probabilidades, se utiliza la distribución normal estándar, que tiene una media de 0 y una desviación estándar de 1. Cualquier variable normal puede estandarizarse usando la siguiente fórmula:\n\n**Formula de Estandarización (puntuación Z):**\n\n$$Z=x−μσ\nZ=σx−μ​$$\n\nLa puntuación Z nos dice cuántas desviaciones estándar está un valor dado de la media. Luego, se usan tablas o software estadístico para encontrar las probabilidades correspondientes.\n\n<br>\n\n**Ejercicios**\n\n Ejercicio 6.7 \n\nUn investigador cientíﬁco informa que unos ratones vivirán un promedio de 40 meses cuando sus dietas se restringen drásticamente y después se enriquecen con vitaminas y proteínas. Suponiendo que la vidas de tales ratones se distribuyen normalmente con una desviación estándar de 6.3 meses, encuentre la probabilidad de que un ratón dado vivirá:\n\n**a)** más de 32 meses<br>**b)** menos de 28 meses<br>**c)** entre 37 y 49 meses\n\n- **Parametros**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmedia <- 40 \ndesviacion_estandar <- 6.3 \n```\n:::\n\n\n**Solución a los incisos**\n\n::: panel-tabset\n#### Inciso A\n\nCual es probabilidad de que un ratón dado vivirá más de 32 meses.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nprob_mas_de_32 <- 1 - pnorm(32, mean = media, sd = desviacion_estandar)\ncat(\"a)\", round(prob_mas_de_32, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\na) 0.8979 \n```\n\n\n:::\n:::\n\n\nLa probabilidad de que un ratón viva más de 32 meses es 0.8979.\n\n**Grafica**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmedia <- 40\ndesviacion_estandar <- 6.3\nrango <- c(media - 3 * desviacion_estandar, media + 3 * desviacion_estandar)\nggplot(data.frame(x = rango), aes(x = x)) +  # Curva de la distribución normal\n  stat_function(fun = dnorm, args = list(mean = media, sd = desviacion_estandar), \n                n = 500, color = \"black\") +  # Resaltar el área de interés (X > 32)\n  geom_area(stat = \"function\", fun = dnorm, args = list(mean = media, sd = desviacion_estandar),\n            fill = \"steelblue\", xlim = c(32, rango[2]), alpha = 0.5) +  # Etiquetas y títulos\n  labs(    title = \"Distribucion Normal\",    subtitle = \"Probabilidad de vivir más de 32 meses\",    x = \"Vida en meses\",    y = \"Densidad de Probabilidad\"  ) +  theme_bw() +  # Línea para el valor de 32\n  geom_vline(xintercept = 32, linetype = \"dashed\", color = \"red\") +\n  geom_text(aes(x = 32, y = 0.01, label = \"32 meses\"), hjust = -0.1, vjust = -1)\n```\n\n::: {.cell-output-display}\n![](trabajoestadistica2_files/figure-html/unnamed-chunk-4-1.png){fig-align='center' width=70%}\n:::\n:::\n\n\nLa probabilidad de que un ratón viva más de 32 meses es 89.79%\n\n#### Inciso B\n\nCual es la probabilidad de que un ratón dado vivirá más de 28 meses.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nprob_menos_de_28 <- pnorm(28, mean = media, sd = desviacion_estandar)\ncat(\"b)\", round(prob_menos_de_28, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nb) 0.0284 \n```\n\n\n:::\n:::\n\n\nLa probabilidad de que un ratón viva más de 32 meses es 0.0284.\n\n**Grafica**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmedia <- 40\ndesviacion_estandar <- 6.3\nrango <- c(media - 3 * desviacion_estandar, media + 3 * desviacion_estandar)\nggplot(data.frame(x = rango), aes(x = x)) +  # Curva de la distribución normal\n  stat_function(fun = dnorm, args = list(mean = media, sd = desviacion_estandar), \n                n = 500, color = \"black\") +  # Resaltar el área de interés (X < 28)\n  geom_area(stat = \"function\", fun = dnorm, args = list(mean = media, sd = desviacion_estandar),\n            fill = \"orange\", xlim = c(rango[1], 28), alpha = 0.5) +  # Etiquetas y títulos\n  labs(    title = \"Distribucion Normal\",    subtitle = \"Probabilidad de vivir menos de 28 meses\",    x = \"Vida en meses\",    y = \"Densidad de Probabilidad\"  ) +  theme_bw() +  # Línea para el valor de 28\n  geom_vline(xintercept = 28, linetype = \"dashed\", color = \"red\") +\n  geom_text(aes(x = 28, y = 0.01, label = \"28 meses\"), hjust = 1.1, vjust = -1)\n```\n\n::: {.cell-output-display}\n![](trabajoestadistica2_files/figure-html/unnamed-chunk-6-1.png){fig-align='center' width=70%}\n:::\n:::\n\n\nLa probabilidad de que un ratón viva más de 32 meses es 2.84%.\n\n#### Inciso C\n\nCual es la probabilidad de que un ratón dado vivirá más de 49 meses.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nprob_c_superior <- pnorm(49, mean = media, sd = desviacion_estandar)\nprob_c_inferior <- pnorm(37, mean = media, sd = desviacion_estandar)\nprob_c <- prob_c_superior - prob_c_inferior\ncat(\"c)\", round(prob_c, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nc) 0.6065 \n```\n\n\n:::\n:::\n\n\nLa probabilidad de que un ratón viva más de 32 meses es 0.6065.\n\n**Grafica**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmedia <- 40\ndesviacion_estandar <- 6.3\nrango <- c(media - 3 * desviacion_estandar, media + 3 * desviacion_estandar)\nggplot(data.frame(x = rango), aes(x = x)) +  # Curva de la distribución normal\n  stat_function(fun = dnorm, args = list(mean = media, sd = desviacion_estandar), \n                n = 500, color = \"black\") +  # Resaltar el área de interés (37 < X < 49)\n  geom_area(stat = \"function\", fun = dnorm, args = list(mean = media, sd = desviacion_estandar),\n            fill = \"purple\", xlim = c(37, 49), alpha = 0.5) +  # Etiquetas y títulos\n  labs(    title = \"Distribucion Normal\",    subtitle = \"Probabilidad de vivir entre 37 y 49 meses\",    x = \"Vida en meses\",    y = \"Densidad de Probabilidad\"  ) +  theme_bw() +  # Líneas para los valores de 37 y 49\n  geom_vline(xintercept = 37, linetype = \"dashed\", color = \"red\") +\n  geom_vline(xintercept = 49, linetype = \"dashed\", color = \"red\") +\n  geom_text(aes(x = 37, y = 0.01, label = \"37\"), hjust = 1.1, vjust = -1) +\n  geom_text(aes(x = 49, y = 0.01, label = \"49\"), hjust = -0.1, vjust = -1)\n```\n\n::: {.cell-output-display}\n![](trabajoestadistica2_files/figure-html/unnamed-chunk-8-1.png){fig-align='center' width=70%}\n:::\n:::\n\n\nLa probabilidad de que un ratón viva más de 32 meses es 60.65%.\n:::\n\n<br>\n\n Ejercicio 6.9 \n\nUna máquina expendedora de bebidas gaseosas se regula para que sirva un promedio de 200 mililitros por vaso. Si la cantidad de bebida se distribuye normalmente con una desviación estándar igual a 15 mililitros,\n\n**a)** ¿qué fracción de los vasos contendrá más de 224 mililitros?<br>**b)** ¿cuál es la probabilidad de que un vaso contenga entre 191 y 209 mililitros?<br>**c)** ¿cuántos vasos probablemente se derramarán si se utilizan vasos de 230 mililitros para las siguientes 1000 bebidas?\n\n- **Parametros**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmedia <- 200\ndesviacion_estandar <- 15\n```\n:::\n\n\n**Solución a los incisos**\n\n::: panel-tabset\n#### Inciso A\n\n¿Qué fracción de los vasos contendrá más de 224 mililitros?\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nprob_a <- 1 - pnorm(224, mean = media, sd = desviacion_estandar)\ncat(\"a)\", round(prob_a, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\na) 0.0548 \n```\n\n\n:::\n:::\n\n\nLa probabilidad de que una fraccion de vasos contendrá más de 224 mililitros es 0.0548\n\n**Grafica**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nrango <- c(media - 3 * desviacion_estandar, media + 3 * desviacion_estandar)\nggplot(data.frame(x = rango), aes(x = x)) +\n  stat_function(fun = dnorm, args = list(mean = media, sd = desviacion_estandar)) +\n  geom_area(stat = \"function\", fun = dnorm, args = list(mean = media, sd = desviacion_estandar),\n            fill = \"coral\", xlim = c(224, max(rango)), alpha = 0.6) +\n  labs(    title = \"Probabilidad de que un vaso contenga más de 224 ml\",    x = \"Cantidad de bebida (ml)\",    y = \"Densidad de probabilidad\"  ) +\n  geom_vline(xintercept = 224, linetype = \"dashed\", color = \"red\") +  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](trabajoestadistica2_files/figure-html/unnamed-chunk-11-1.png){fig-align='center' width=70%}\n:::\n:::\n\n\nLa probabilidad de que una fraccion de vasos contendrá más de 224 mililitros es 54.8%.\n\n#### Inciso B\n\n¿Cuál es la probabilidad de que un vaso contenga entre 191 y 209 mililitros?\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmedia <- 200\ndesviacion_estandar <- 15\nprob_b_superior <- pnorm(209, mean = media, sd = desviacion_estandar)\nprob_b_inferior <- pnorm(191, mean = media, sd = desviacion_estandar)\nprob_b <- prob_b_superior - prob_b_inferior\ncat(\"b)\", round(prob_b, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nb) 0.4515 \n```\n\n\n:::\n:::\n\n\nLa probabilidad de que un vaso contenga entre 191 y 209 mililitros es de 0.4515.\n\n**Grafica**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nrango <- c(media - 3 * desviacion_estandar, media + 3 * desviacion_estandar)\nggplot(data.frame(x = rango), aes(x = x)) +\n  stat_function(fun = dnorm, args = list(mean = media, sd = desviacion_estandar)) +\n  geom_area(stat = \"function\", fun = dnorm, args = list(mean = media, sd = desviacion_estandar),\n            fill = \"darkgreen\", xlim = c(191, 209), alpha = 0.6) +\n  labs(    title = \"Probabilidad de un vaso entre 191 ml y 209 ml\",    x = \"Cantidad de bebida (ml)\",    y = \"Densidad de probabilidad\"  ) +\n  geom_vline(xintercept = 191, linetype = \"dashed\", color = \"red\") +\n  geom_vline(xintercept = 209, linetype = \"dashed\", color = \"red\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](trabajoestadistica2_files/figure-html/unnamed-chunk-13-1.png){fig-align='center' width=70%}\n:::\n:::\n\n\nLa probabilidad de que un vaso contenga entre 191 y 209 mililitros es de 45.15%.\n\n#### Inciso C\n\n¿Cuántos vasos probablemente se derramarán si se utilizan vasos de 230 mililitros para las siguientes 1000 bebidas?\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmedia <- 200\ndesviacion_estandar <- 15\ntotal_vasos <- 1000\nprob_derramarse <- 1 - pnorm(230, mean = media, sd = desviacion_estandar)\nvasos_derramados <- prob_derramarse * total_vasos\ncat(\"c)\", round(vasos_derramados), \"vasos\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nc) 23 vasos\n```\n\n\n:::\n:::\n\n\nSi se utilizan vasos de 230 mililitros para las siguientes 1000 bebidas probablemente se derramarán 23 vasos.\n\n**Grafica**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nrango <- c(media - 3 * desviacion_estandar, media + 3 * desviacion_estandar)\nggplot(data.frame(x = rango), aes(x = x)) +\n  stat_function(fun = dnorm, args = list(mean = media, sd = desviacion_estandar)) +\n  geom_area(stat = \"function\", fun = dnorm, args = list(mean = media, sd = desviacion_estandar),\n            fill = \"purple\", xlim = c(230, max(rango)), alpha = 0.6) +\n  labs(    title = \"Probabilidad de que un vaso se derrame\",    x = \"Cantidad de bebida (ml)\",    y = \"Densidad de probabilidad\"  ) +\n  geom_vline(xintercept = 230, linetype = \"dashed\", color = \"red\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](trabajoestadistica2_files/figure-html/unnamed-chunk-15-1.png){fig-align='center' width=70%}\n:::\n:::\n\n\nSi se utilizan vasos de 230 mililitros para las siguientes 1000 bebidas probablemente se derramarán 23 vasos.\n:::\n\n<br>\n\nEjercicio 6.11 \n\nUn abogado viaja todos los días de su casa en los suburbios a su oﬁ cina en el centro de la ciudad. El tiempo promedio para un viaje sólo de ida es 24 minutos, con una desviación estándar de 3.8 minutos. Suponga que la distribución de los tiempos de viaje está distribuida normalmente.\n\n**a)** ¿Cuál es la probabilidad de que un viaje tome al menos 1/2 hora?<br> **b)** Si la oﬁcina abre a las 9:00 A.M. y él sale diario de su casa a las 8:45 A.M., ¿qué porcentaje de las veces llegará tarde al trabajo?<br>**c)** Si sale de su casa a las 8:35 A.M. y el café se sirve en la oﬁcina de 8:50 A.M. a 9:00 A.M., cuál es la probabilidad de que se pierda el café?<br>**d)** Encuentre la longitud de tiempo por arriba de la cual encontramos e1 15% de los viajes más lentos.<br>**e)** Encuentre la probabilidad de que 2 de los siguientes 3 viajes tomen al menos 1/2 hora.<br>\n\n- **Parametros**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmedia <- 24\ndesviacion <- 3.8\n```\n:::\n\n\n**Solución a los incisos**\n\n:::: panel-tabset\n#### Inciso A\n\n¿Cuál es la probabilidad de que un viaje tome al menos 1/2 hora?\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmedia <- 24\ndesviacion <- 3.8\nprob_a <- 1 - pnorm(30, mean = media, sd = desviacion)\ncat(\"a)\", round(prob_a, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\na) 0.0572 \n```\n\n\n:::\n:::\n\n\nLa probabilidad de que un viaje tome al menos 1/2 hora es de 0.0572.\n\n**Grafica**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nrango <- c(media - 3 * desviacion, media + 3 * desviacion)\nggplot(data.frame(x = rango), aes(x = x)) +\n  stat_function(fun = dnorm, args = list(mean = media, sd = desviacion), n = 500) +\n  geom_area(stat = \"function\", fun = dnorm, args = list(mean = media, sd = desviacion), fill = \"coral\", xlim = c(30, max(rango)), alpha = 0.6) +\n  labs(title = \"Distribucion Normal\", x = \"Tiempo de viaje (minutos)\", y = \"Densidad de Probabilidad\") +\n  geom_vline(xintercept = 30, linetype = \"dashed\", color = \"red\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](trabajoestadistica2_files/figure-html/unnamed-chunk-18-1.png){fig-align='center' width=70%}\n:::\n:::\n\n\nLa probabilidad de que un viaje tome al menos 1/2 hora es de 5.72%.\n\n#### Inciso B\n\nSi la oﬁcina abre a las 9:00 A.M. y él sale diario de su casa a las 8:45 A.M., ¿qué porcentaje de las veces llegará tarde al trabajo?\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nprob_b <- 1 - pnorm(15, mean = media, sd = desviacion)\nporcentaje_b <- prob_b * 100\ncat(\"b)\", round(porcentaje_b, 2), \"%\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nb) 99.11 %\n```\n\n\n:::\n:::\n\n\nSi la oﬁcina abre a las 9:00 A.M. y él sale diario de su casa a las 8:45 A.M. 99.11 %xxx llegará tarde al trabajo.\n\n**Grafica**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nrango <- c(media - 3 * desviacion, media + 3 * desviacion)\nggplot(data.frame(x = rango), aes(x = x)) +\n  stat_function(fun = dnorm, args = list(mean = media, sd = desviacion), n = 500) +\n  geom_area(stat = \"function\", fun = dnorm, args = list(mean = media, sd = desviacion),fill = \"#3de3c2\", xlim = c(15, max(rango)), alpha = 0.6) +\n  labs(title = \"Distribucion Normal\", x = \"Tiempo de viaje (minutos)\", y = \"Densidad de Probabilidad\") +\n  geom_vline(xintercept = 15, linetype = \"dashed\", color = \"red\") +  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](trabajoestadistica2_files/figure-html/unnamed-chunk-20-1.png){fig-align='center' width=70%}\n:::\n:::\n\n\nSi la oﬁcina abre a las 9:00 A.M. y él sale diario de su casa a las 8:45 A.M. 99.11 % llegará tarde al trabajo.\n\n#### Inciso C\n\nSi sale de su casa a las 8:35 A.M. y el café se sirve en la oﬁcina de 8:50 A.M. a 9:00 A.M., cuál es la probabilidad de que se pierda el café?\n\n::: callout-warning\n## Advertencia\n\nEste inciso es un problema de distribución binomial, no normal, ya que se trata de un número discreto de “éxitos” (viajes de más de 30 minutos) en un número fijo de intentos (3 viajes). Por lo tanto, la gráfica no es una curva de densidad normal, sino un gráfico de barras de la distribución binomial.\n:::\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nprob_c_antes <- pnorm(15, mean = media, sd = desviacion)\nprob_c_despues <- 1 - pnorm(25, mean = media, sd = desviacion)\nprob_c <- prob_c_antes + prob_c_despues\ncat(\"c)\", round(prob_c, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nc) 0.4051 \n```\n\n\n:::\n:::\n\n\nLa probabilidad de que se pierda el café es de 0.4051.\n\n**Grafica**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nrango <- c(media - 3 * desviacion, media + 3 * desviacion)\nggplot(data.frame(x = rango), aes(x = x)) +\n  stat_function(fun = dnorm, args = list(mean = media, sd = desviacion), n = 500) +\n  geom_area(stat = \"function\", fun = dnorm, args = list(mean = media, sd = desviacion), fill = \"gray\", xlim = c(min(rango), 15), alpha = 0.6) +\n  geom_area(stat = \"function\", fun = dnorm, args = list(mean = media, sd = desviacion), fill = \"gray\", xlim = c(25, max(rango)), alpha = 0.6) +\n  labs(title = \"Distribucion Normal\", subtitle = \"Probabilidad de perder el café\", x = \"Tiempo de viaje (minutos)\", y = \"Densidad de Probabilidad\") +\n  geom_vline(xintercept = 15, linetype = \"dashed\", color = \"red\") +\n  geom_vline(xintercept = 25, linetype = \"dashed\", color = \"red\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](trabajoestadistica2_files/figure-html/unnamed-chunk-22-1.png){fig-align='center' width=70%}\n:::\n:::\n\n\nLa probabilidad de que se pierda el café es de 40.51%.\n\n#### Inciso D\n\nEncuentre la longitud de tiempo por arriba de la cual encontramos e1 15% de los viajes más lentos.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nvalor_d <- qnorm(0.85, mean = media, sd = desviacion)\ncat(\"d)\", round(valor_d, 2), \"minutos\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nd) 27.94 minutos\n```\n\n\n:::\n:::\n\n\nLa longitud de tiempo por arriba de la cual encontramos e1 15% de los viajes más lentos es 27.94 minutos.\n\n**Grafica**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmedia <- 24\ndesviacion <- 3.8\nvalor_cuantil <- qnorm(0.85, mean = media, sd = desviacion)\nrango <- c(media - 3 * desviacion, media + 3 * desviacion)\nlibrary(ggplot2)\nggplot(data.frame(x = rango), aes(x = x)) +\n  stat_function(fun = dnorm, args = list(mean = media, sd = desviacion), n = 500) +\n  geom_area(stat = \"function\", fun = dnorm, args = list(mean = media, sd = desviacion), fill = \"#11de07\", xlim = c(valor_cuantil, max(rango)), alpha = 0.6) +\n  labs(    title = \"Distribucion Normal\", subtitle = \"Viajes más lentos (15% superior)\",    x = \"Tiempo de viaje (minutos)\",    y = \"Densidad de Probabilidad\"  ) +\n  geom_vline(xintercept = valor_cuantil, linetype = \"dashed\", color = \"red\") +\n  geom_text(aes(x = valor_cuantil, y = dnorm(valor_cuantil, mean = media, sd = desviacion), label = paste0(round(valor_cuantil, 2), \" min\")), vjust = -1, hjust = -0.1) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](trabajoestadistica2_files/figure-html/unnamed-chunk-24-1.png){fig-align='center' width=70%}\n:::\n:::\n\n\nLa longitud de tiempo por arriba de la cual encontramos e1 15% de los viajes más lentos es 27.94 minutos.\n\n#### Inciso E\n\nEncuentre la probabilidad de que 2 de los siguientes 3 viajes tomen al menos 1/2 hora.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\np_exito <- 1 - pnorm(30, mean = media, sd = desviacion)\nn_viajes <- 3\nx_exitos <- 2\nprob_e <- dbinom(x_exitos, size = n_viajes, prob = p_exito)\ncat(\"e)\", round(prob_e, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ne) 0.0092 \n```\n\n\n:::\n:::\n\n\nLa probabilidad de que 2 de los siguientes 3 viajes tomen al menos 1/2 hora es 0.0092.\n\n**Grafica**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\np_exito <- 1 - pnorm(30, mean = 24, sd = 3.8) \nn_viajes <- 3 \nexitos_deseados <- 0:n_viajes\nprobabilidades <- dbinom(exitos_deseados, size = n_viajes, prob = p_exito)\ndf_binomial <- data.frame( num_exitos = factor(exitos_deseados),  prob = probabilidades)\nlibrary(ggplot2)\nggplot(df_binomial, aes(x = num_exitos, y = prob)) +\n  geom_bar(stat = \"identity\", fill = \"skyblue\") +\n  geom_text(aes(label = round(prob, 4)), vjust = -0.5) +\n  labs(    title = \"Distribución Binomial de viajes que tardan ≥ 30 minutos\",   subtitle = \"La probabilidad de tener exactamente 2 'éxitos' es del 0.94%\", x = \"Número de viajes de al menos 30 minutos\",   y = \"Probabilidad\"  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](trabajoestadistica2_files/figure-html/unnamed-chunk-26-1.png){fig-align='center' width=70%}\n:::\n:::\n\n\nLa probabilidad de que 2 de los siguientes 3 viajes tomen al menos 1/2 hora es 0.92%.\n::::\n\n<br>\n\n Ejercicio 6.13 \n\nLa vida promedio de cierto tipo de motor pequeño es de 10 años con una desviación estándar de 2 años. El fabricante reemplaza gratis todos los motores que fallen dentro del periodo de garantía. Si él está dispuesto a reemplazar sólo 3% de los motores que fallan, ¿cuánto tiempo de garantía debería ofrecer? Suponga que la duración de un motor sigue una distribución normal.\n\n- **Parametros**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmedia <- 10       \ndesviacion <- 2    \nprobabilidad_fallo <- 0.03 \n```\n:::\n\n\n**Solución**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ntiempo_garantia <- qnorm(probabilidad_fallo, mean = media, sd = desviacion)\ncat(\"El fabricante debería ofrecer una garantía de:\", round(tiempo_garantia, 2), \"años\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nEl fabricante debería ofrecer una garantía de: 6.24 años\n```\n\n\n:::\n:::\n\n\n**Grafica**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmedia <- 10\ndesviacion <- 2\ntiempo_garantia <- qnorm(0.03, mean = media, sd = desviacion)\nrango <- c(media - 3 * desviacion, media + 3 * desviacion)\nggplot(data.frame(x = rango), aes(x = x)) +\n   stat_function(fun = dnorm, args = list(mean = media, sd = desviacion), n = 500, color = \"black\") +  \n  geom_area(stat = \"function\", fun = dnorm, args = list(mean = media, sd = desviacion),  fill = \"purple\", xlim = c(min(rango), tiempo_garantia), alpha = 0.6) + \n  labs(    title = \"Período de Garantía de los Motores\",    subtitle = \"El 3% de los motores fallará antes del período de garantía\",    x = \"Vida útil del motor (años)\",    y = \"Densidad de Probabilidad\"  ) +\n  theme_bw() +\n  geom_vline(xintercept = tiempo_garantia, linetype = \"dashed\", color = \"red\") +\n  geom_text(aes(x = tiempo_garantia, y = 0.01, label = paste0(round(tiempo_garantia, 2), \" años\")), \n            hjust = 1.1, vjust = -1)\n```\n\n::: {.cell-output-display}\n![](trabajoestadistica2_files/figure-html/unnamed-chunk-29-1.png){fig-align='center' width=70%}\n:::\n:::\n\n\nEl fabricante debería ofrecer una garantía de 6.24 años.\n\n------------------------------------------------------------------------\n\n Ejercicio 6.15 \n\nUna compañía paga a sus empleados un salario promedio de \\$15.90 por hora con una desviación estándar de \\$1.50. Si los salarios se distribuyen aproximadamentede forma normal y se pagan al centavo más 6.15 Una compañía paga a sus empleados un salario promedio de \\$15.90 por hora con una desviación estándar de \\$1.50. Si los salarios se distribuyen aproximadamente de forma normal y se pagan al centavo más 6.15 Una compañía paga a sus empleados un salario promedio de \\$15.90 por hora con una desviación estándar de \\$1.50. Si los salarios se distribuyen aproximadamente de forma normal y se pagan al centavo más cercano\n\n**a)** ¿qué porcentaje de los trabajadores reciben salarios entre \\$13.75 y \\$16.22 inclusive por hora?<br>**b)** ¿el 5% más alto de los salarios por hora de los empleados es mayor a qué cantidad?\n\n- **Parametros**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmedia <- 15.90\ndesviacion <- 1.50\nlimite_inferior <- 13.75 - 0.005\nlimite_superior <- 16.22 + 0.005\n```\n:::\n\n\n**Solución a los incisos**\n\n::: panel-tabset\n#### Inciso A\n\n¿Qué porcentaje de los trabajadores reciben salarios entre \\$13.75 y \\$16.22 inclusive por hora?\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nprob_a_superior <- pnorm(limite_superior, mean = media, sd = desviacion)\nprob_a_inferior <- pnorm(limite_inferior, mean = media, sd = desviacion)\nprob_a <- prob_a_superior - prob_a_inferior\nporcentaje_a <- prob_a * 100\ncat(\"a)\", round(porcentaje_a, 2), \"%\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\na) 51.04 %\n```\n\n\n:::\n:::\n\n\n**Grafica**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nrango <- c(media - 3 * desviacion, media + 3 * desviacion)\nggplot(data.frame(x = rango), aes(x = x)) +\n  stat_function(fun = dnorm, args = list(mean = media, sd = desviacion), n = 500) +\n  geom_area(stat = \"function\", fun = dnorm, args = list(mean = media, sd = desviacion), fill = \"darkgreen\", xlim = c(limite_inferior, limite_superior), alpha = 0.6) +\n  labs(    title = \"Porcentaje de salarios entre $13.75 y $16.22\",  x = \"Salario por hora ($)\", y = \"Densidad de probabilidad\"  ) +\n  geom_vline(xintercept = c(limite_inferior, limite_superior), linetype = \"dashed\", color = \"red\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](trabajoestadistica2_files/figure-html/unnamed-chunk-32-1.png){fig-align='center' width=70%}\n:::\n:::\n\n\nEl porcentaje de trabajadores con salarios entre \\$13.75 y \\$16.22 es 51.04 %.\n\n#### Inciso B\n\n¿El 5% más alto de los salarios por hora de los empleados es mayor a qué cantidad?\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmedia <- 15.90\ndesviacion <- 1.50\nvalor_b <- qnorm(0.95, mean = media, sd = desviacion)\ncat(\"b)\", round(valor_b, 2), \"$\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nb) 18.37 $\n```\n\n\n:::\n:::\n\n\nEl 5% más alto de los salarios es mayor a \\$18.37.\n\n**Grafica**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nrango <- c(media - 3 * desviacion, media + 3 * desviacion)\nggplot(data.frame(x = rango), aes(x = x)) +\n  stat_function(fun = dnorm, args = list(mean = media, sd = desviacion), n = 500) +\n  geom_area(stat = \"function\", fun = dnorm, args = list(mean = media, sd = desviacion), fill = \"purple\", xlim = c(valor_b, max(rango)), alpha = 0.6) +\n  labs(    title = \"El 5% de salarios más altos\",  x = \"Salario por hora ($)\", y = \"Densidad de probabilidad\" ) +\n  geom_vline(xintercept = valor_b, linetype = \"dashed\", color = \"red\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](trabajoestadistica2_files/figure-html/unnamed-chunk-34-1.png){fig-align='center' width=70%}\n:::\n:::\n\n\nEl 5% más alto de los salarios es mayor a \\$18.37.\n:::\n\n<br>\n\n## **Shiny Interactivo Dostribucion Normal**\n\n```{shinylive-r}\n#| standalone: true\n#| viewerHeight: 550\n\nlibrary(shiny)\nlibrary(ggplot2)\n\nui <- fluidPage(\n  titlePanel(\"Distribución Normal\"),\n  \n  sidebarLayout(\n    sidebarPanel(\n      h4(\"Parámetros de la Distribución\"),\n      numericInput(\"norm_mean\", \"Media (μ):\", value = 0),\n      numericInput(\"norm_sd\", \"Desviación Estándar (σ):\", value = 1, min = 0.1, step = 0.1)\n    ),\n    \n    mainPanel(\n      plotOutput(\"dist_plot\", height = \"480px\")\n    )\n  )\n)\n\nserver <- function(input, output) {\n  output$dist_plot <- renderPlot({\n    mean_val <- input$norm_mean\n    sd_val <- input$norm_sd\n    \n    # Rango de visualización (4 desviaciones estándar)\n    x_min <- mean_val - 4 * sd_val\n    x_max <- mean_val + 4 * sd_val\n    \n    g <- ggplot() + \n      theme_minimal() +\n      theme(\n        plot.title = element_text(size = 14, face = \"bold\", hjust = 0.5),\n        axis.title = element_text(size = 11),\n        legend.position = \"bottom\"\n      ) +\n      stat_function(fun = dnorm, args = list(mean = mean_val, sd = sd_val),\n                    linewidth = 1.2, aes(color = \"Normal Teórica\")) +\n      xlim(x_min, x_max) +\n      scale_color_manual(values = c(\"Normal Teórica\" = \"#2C3E50\")) +\n      labs(title = paste0(\"Distribución Normal: N(μ = \", mean_val, \", σ = \", sd_val, \")\"),\n           x = \"Valores (X)\", y = \"Densidad\", color = \"\")\n    \n    print(g)\n  })\n}\n\nshinyApp(ui = ui, server = server)\n```\n\n\n<br>\n\n# Distribucion Ji Cuadrado\n\nLa distribución ji-cuadrado $x^2$ es una distribución de probabilidad continua definida solo para valores positivos, que surge de la suma de los cuadrados de variables normales estándar independientes, dependiendo de un parámetro llamado grados de libertad (𝑘). Su media es 𝑘, su varianza 2𝑘 y su forma varía según 𝑘: es muy asimétrica para valores pequeños y se aproxima a una normal al crecer. Su función de densidad se expresa mediante la función gamma, y es fundamental en estadística porque se utiliza en pruebas de hipótesis (bondad de ajuste e independencia en tablas de contingencia), en la construcción de intervalos de confianza para varianzas y en la base de otras distribuciones como la t de Student y la F de Fisher. En términos intuitivos, mide la dispersión total al sumar cuadrados de desviaciones de normales, por lo que resulta clave para analizar varianzas y asociaciones entre variables.\n\n**Parámetros y Características**\n\nA diferencia de la distribución normal, la distribución ji cuadrado no está definida por una media y una desviación estándar, sino por un único parámetro:\n\n**Grados de libertad (v o df):** Este parámetro determina la forma de la distribución. A medida que los grados de libertad aumentan, la forma de la distribución se vuelve más simétrica y se aproxima a una distribución normal.\n\n**Valores No Negativos:** La variable ji cuadrado $x^2$ solo puede tomar valores positivos, ya que se calcula a partir de la suma de cuadrados. Por lo tanto, su curva comienza en cero y se extiende hacia la derecha.\n\n**Asimétrica a la Derecha:** La distribución es asimétrica con una cola larga hacia la derecha.\n\n**Media y Varianza:** La media de la distribución es igual a los grados de libertad (μ=v), y la varianza es el doble de los grados de libertad ($\\sigma^2 = 2v$)\n\n**Dominio: 𝑋≥0** (nunca toma valores negativos).\n\n**Función de densidad de probabilidad**\n\n$$f(x; k) = \\frac{1}{2^{k/2} \\Gamma\\left(\\frac{k}{2}\\right)} x^{\\frac{k}{2} - 1} e^{-x/2}, \\quad x > 0$$\n\n**Usos principales en la estadística**\n\nLa $x^2$ es fundamental en **estadística inferencial**. Algunos de sus usos:\n\n**Pruebas de hipótesis:**\n\n1.  **Chi-cuadrado de bondad de ajuste:** verificar si los datos observados se ajustan a una distribución teórica.\n\n2.  **Chi-cuadrado de independencia:** evaluar si dos variables categóricas son independientes en una tabla de contingencia.\n\n**Intervalos de confianza:** para la **varianza poblacional** de una normal, ya que está relacionada con la suma de cuadrados de normales.\n\n**Modelos más complejos:** forma parte de la familia de distribuciones asociadas a la **F de Fisher** y la **t de Student**, que también dependen de $x^2$\n\n**Familias de Curvas Chi Cuadrado**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nk_vals <- c(4, 5, 10)\nx <- seq(0, 40, length.out = 1000)\ndf <- data.frame()\nfor (k in k_vals) {  df <- rbind(df, data.frame(  x = x,    dens = dchisq(x, df = k),    k = factor(k)  ))}\nggplot(df, aes(x = x, y = dens, color = k)) +\n  geom_line(size = 1.2) +\n  labs(    title = \"Familia de curvas χ²\",    subtitle = \"Densidades para distintos grados de libertad\",    x = \"x\",\n    y = \"Densidad\",    color = \"Grados de libertad (k)\"  ) +\n  theme_minimal(base_size = 14)\n```\n\n::: {.cell-output-display}\n![](trabajoestadistica2_files/figure-html/unnamed-chunk-35-1.png){fig-align='center' width=70%}\n:::\n:::\n\n\n**Ejercicios**\n\n**Ejercicio 8.39**\n\nPara una distribución chi cuadrada encuentre\n\na.  $\\chi_{0.025}^{2}$ cuando $v = 15$;\n\nb.  $\\chi_{0.01}^{2}$ cuando $v = 7$;\n\nc.  $\\chi_{0.05}^{2}$ cuando $v = 24.$\n\n**Solucion a los incisos**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\na <- qchisq(0.025, df = 15, lower.tail = FALSE)\nb <- qchisq(0.01, df = 7, lower.tail = FALSE)\nc <- qchisq(0.05, df = 24, lower.tail = FALSE)\na; b; c\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 27.48839\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 18.47531\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 36.41503\n```\n\n\n:::\n:::\n\n\n**Gráficas**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\na <- qchisq(0.025, df = 15, lower.tail = FALSE)\nb <- qchisq(0.01, df = 7, lower.tail = FALSE)\nc <- qchisq(0.05, df = 24, lower.tail = FALSE)\ngrafico_chi <- function(df, alpha, critico, titulo){\n  x <- seq(0, critico + df*2, 0.1)  # eje x extendido\n  dens <- dchisq(x, df)\n  data <- data.frame(x = x, y = dens)\n  ggplot(data, aes(x, y)) +\n    geom_line(color = \"blue\", size = 1.2) +\n    geom_area(data = subset(data, x >= critico), aes(x, y),  fill = \"red\", alpha = 0.5) +\n    geom_vline(xintercept = critico, linetype = \"dashed\", color = \"red\", size = 1) +\n    labs(title = titulo, subtitle = paste(\"df =\", df, \", α =\", alpha, \", crítico =\", round(critico,2)), x = \"x\", y = \"Densidad\") +    theme_minimal(base_size = 14)}\ng1 <- grafico_chi(df = 15, alpha = 0.025, critico = a, titulo = \"Distribución Chi-cuadrado (a)\")\ng2 <- grafico_chi(df = 7, alpha = 0.01, critico = b, titulo = \"Distribución Chi-cuadrado (b)\")\ng3 <- grafico_chi(df = 24, alpha = 0.05, critico = c, titulo = \"Distribución Chi-cuadrado (c)\")\ng1; g2; g3\n```\n\n::: {.cell-output-display}\n![](trabajoestadistica2_files/figure-html/unnamed-chunk-37-1.png){fig-align='center' width=70%}\n:::\n\n::: {.cell-output-display}\n![](trabajoestadistica2_files/figure-html/unnamed-chunk-37-2.png){fig-align='center' width=70%}\n:::\n\n::: {.cell-output-display}\n![](trabajoestadistica2_files/figure-html/unnamed-chunk-37-3.png){fig-align='center' width=70%}\n:::\n:::\n\n\n**Ejercicio 8.41**\n\nPara una distribución chi cuadrada encuentre $(\\chi_{\\alpha}^2)$ tal que\n\na.  $P(X^2 > \\chi_{\\alpha}^2) = 0.99$ cuando $v = 4$;\n\nb.  $P(X^2 > \\chi_{\\alpha}^2) = 0.025$ cuando $v = 19$;\n\nc.  $P(37.652 < X^2 < \\chi_{\\alpha}^2) = 0.045$ cuando $v = 25.$\n\n**Solucion a los incisos**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\na <- qchisq(0.99, df = 4, lower.tail = FALSE)\nb <- qchisq(0.025, df = 19, lower.tail = FALSE)\np_base <- pchisq(37.652, df = 25)\np_objetivo <- p_base + 0.045\nc <- qchisq(p_objetivo, df = 25)\na; b; c\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.2971095\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 32.85233\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 46.92392\n```\n\n\n:::\n:::\n\n\n**Gráficas**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nplot_chisq <- function(df, region, alpha = 0.05, case = \"a\") {\n  x <- seq(0, qchisq(0.999, df), length.out = 1000)\n  y <- dchisq(x, df)\n  data <- data.frame(x = x, y = y)\n  if (case == \"a\" | case == \"b\") {    shade <- subset(data, x > region)  }\n  else if (case == \"c\") {shade <- subset(data, x > 37.652 & x < region)  }\n  ggplot(data, aes(x, y)) +\n    geom_line(color = \"blue\", size = 1) +\n    geom_area(data = shade, aes(x, y), fill = \"red\", alpha = 0.4) +\n    labs(  title = paste(\"Distribución Chi-cuadrado con v =\", df), subtitle = paste(\"Caso\", case, \"con región sombreada\"),      x = \"X²\", y = \"Densidad\"    ) +\n    theme_minimal()}\nchi_a <- qchisq(0.01, df = 4)\nplot_chisq(df = 4, region = chi_a, case = \"a\")\n```\n\n::: {.cell-output-display}\n![](trabajoestadistica2_files/figure-html/unnamed-chunk-39-1.png){fig-align='center' width=70%}\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nchi_b <- qchisq(0.975, df = 19)\nplot_chisq(df = 19, region = chi_b, case = \"b\")\n```\n\n::: {.cell-output-display}\n![](trabajoestadistica2_files/figure-html/unnamed-chunk-40-1.png){fig-align='center' width=70%}\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\np_left <- pchisq(37.652, df = 25)\ntarget_prob <- p_left + 0.045\nchi_c <- qchisq(target_prob, df = 25)\nplot_chisq(df = 25, region = chi_c, case = \"c\")\n```\n\n::: {.cell-output-display}\n![](trabajoestadistica2_files/figure-html/unnamed-chunk-41-1.png){fig-align='center' width=70%}\n:::\n:::\n\n<br>\n\n## **Shiny Interactivo Dostribucion Ji-Cuadrado**\n\n```{shinylive-r}\n#| standalone: true\n#| viewerHeight: 550\n\nlibrary(shiny)\nlibrary(ggplot2)\n\nui <- fluidPage(\n  titlePanel(\"Distribución Ji-Cuadrado (χ²)\"),\n  \n  sidebarLayout(\n    sidebarPanel(\n      h4(\"Parámetros de la Distribución\"),\n      sliderInput(\"chisq_df\", \"Grados de libertad (k):\", min = 1, max = 100, value = 4, step = 1),\n      checkboxInput(\"show_norm_chisq\", \"Mostrar aproximación Normal teórica\", FALSE)\n    ),\n    \n    mainPanel(\n      plotOutput(\"dist_plot\", height = \"480px\")\n    )\n  )\n)\n\nserver <- function(input, output) {\n  output$dist_plot <- renderPlot({\n    df_val <- input$chisq_df\n    \n    # Rango dinámico según los grados de libertad\n    x_max <- max(20, df_val + 4 * sqrt(2 * df_val))\n    \n    g <- ggplot() + \n      theme_minimal() +\n      theme(\n        plot.title = element_text(size = 14, face = \"bold\", hjust = 0.5),\n        axis.title = element_text(size = 11),\n        legend.position = \"bottom\"\n      ) +\n      stat_function(fun = dchisq, args = list(df = df_val),\n                    linewidth = 1.2, aes(color = \"Ji-Cuadrado (χ²)\")) +\n      xlim(0, x_max) +\n      labs(title = paste0(\"Distribución Ji-Cuadrado con \", df_val, \" Grados de Libertad\"),\n           x = \"Valores (X)\", y = \"Densidad\", color = \"\")\n      \n    # Añadir aproximación normal si se activa el checkbox\n    if (input$show_norm_chisq) {\n      g <- g + stat_function(fun = dnorm, args = list(mean = df_val, sd = sqrt(2 * df_val)),\n                             linewidth = 1, linetype = \"dashed\", aes(color = \"Aproximación Normal\"))\n      color_map <- c(\"Ji-Cuadrado (χ²)\" = \"#D35400\", \"Aproximación Normal\" = \"#7F8C8D\")\n    } else {\n      color_map <- c(\"Ji-Cuadrado (χ²)\" = \"#D35400\")\n    }\n    \n    g <- g + scale_color_manual(values = color_map)\n    print(g)\n  })\n}\n\nshinyApp(ui = ui, server = server)\n```\n\n<br>\n\n\n# Distribucion T de Student\n\nLa **distribución *t* de Student** es una distribución de probabilidad continua que surge al estimar la media de una población normalmente distribuida cuando el tamaño de la muestra es pequeño y la varianza poblacional es desconocida. Fue introducida en 1908 por William Sealy Gosset bajo el seudónimo de *Student*.\n\nMatemáticamente, si Z es una variable aleatoria con distribución normal estándar N(0,1) y V es una variable con distribución chi-cuadrado con v grados de libertad, independientes entre sí, entonces la variable\n\n$$T = \\frac{Z}{\\sqrt{V / v}}$$\n\nsigue una distribución *t* de Student con v grados de libertad.\n\n**Principales características**\n\n- **Forma**: es simétrica respecto al cero, similar a la normal estándar, pero con colas más pesadas (mayor probabilidad en los extremos).\n\n- **Parámetro**: depende de los grados de libertad (vv); a mayor vv, la distribución se aproxima a la normal estándar N(0,1).\n\n- **Media**: 0 (para v\\>1v \\> 1).\n\n- **Varianza**: $$\\text{Var}(T) = \\frac{v}{v - 2} \\quad \\text{para } v > 2$$\n\n**Usos principales**\n\n- Pruebas de hipótesis sobre medias (prueba *t* de Student)\n\n- Construcción de intervalos de confianza para la medias\n\n- Modelar incertidumbre en muestras pequeñas\n\n**Familia de Curvas para T de Student**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(123)\ndfs <- c(3, 5, 10)          # grados de libertad a mostrar\nx_range <- seq(-5, 5, by = 0.01)\ndf_t <- expand_grid(x = x_range, df = dfs) |>\n  mutate(dens = dt(x, df))\nggplot(df_t, aes(x = x, y = dens, color = factor(df), group = df)) +\n  geom_line(size = 1) +\n  labs(    title = \"Familia de curvas t-Student\",    subtitle = \"Diferentes grados de libertad (df)\",    x = \"x\",\n    y = \"Densidad\",    color = \"df\"  ) +\n  theme_minimal(base_size = 12)\n```\n\n::: {.cell-output-display}\n![](trabajoestadistica2_files/figure-html/unnamed-chunk-42-1.png){fig-align='center' width=70%}\n:::\n:::\n\n\n**Ejercicio 1**\n\n**8.47**\\\na) Encuentre $P(T < 2.365)$ cuando $v = 7$.\n\nb.  Encuentre $P(T > 1.318)$ cuando $v = 24$.\n\nc.  Encuentre $P(-1.356 < T < 2.179)$ cuando $v = 12$.\n\nd.  Encuentre $P(T > -2.567)$ cuando $v = 17$.\n\n**Solucion**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\na <- pt(2.365, df = 7)\nb <- 1 - pt(1.318, df = 24)\nc <- pt(2.179, df = 12) - pt(-1.356, df = 12)\nd <- 1 - pt(-2.567, df = 17)\nresults <- data.frame(\n  Inciso = c(\"a\", \"b\", \"c\", \"d\"),\n  Resultado = c(a, b, c, d)\n)\nprint(results)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Inciso  Resultado\n1      a 0.97501381\n2      b 0.09997295\n3      c 0.87497477\n4      d 0.99000136\n```\n\n\n:::\n:::\n\n\nGráficas\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nplot_t <- function(df, region = c(\"left\", \"right\", \"between\"), \n                   value1, value2 = NULL, title = \"\") {\n  x <- seq(-4, 4, length.out = 1000)\n  dens <- dt(x, df)\n  data <- data.frame(x = x, y = dens)\n  if(region == \"left\"){\n    data$shade <- ifelse(data$x <= value1, data$y, NA)\n  } else if(region == \"right\"){\n    data$shade <- ifelse(data$x >= value1, data$y, NA)\n  } else if(region == \"between\"){\n    data$shade <- ifelse(data$x >= value1 & data$x <= value2, data$y, NA)\n }\n  ggplot(data, aes(x, y)) +\n    geom_line(color = \"blue\", size = 1) +\n    geom_area(aes(y = shade), fill = \"red\", alpha = 0.4) +\n    labs(title = title,  subtitle = paste(\"Distribución t con v =\", df), x = \"t\", y = \"Densidad\") +\n    theme_minimal()\n}\nplot_t(df = 7, region = \"left\", value1 = 2.365, \n       title = \"a) P(T < 2.365), v = 7\")\n```\n\n::: {.cell-output-display}\n![](trabajoestadistica2_files/figure-html/unnamed-chunk-44-1.png){fig-align='center' width=70%}\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nplot_t(df = 24, region = \"right\", value1 = 1.318, \n       title = \"b) P(T > 1.318), v = 24\")\n```\n\n::: {.cell-output-display}\n![](trabajoestadistica2_files/figure-html/unnamed-chunk-45-1.png){fig-align='center' width=70%}\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nplot_t(df = 12, region = \"between\", value1 = -1.356, value2 = 2.179, \n       title = \"c) P(-1.356 < T < 2.179), v = 12\")\n```\n\n::: {.cell-output-display}\n![](trabajoestadistica2_files/figure-html/unnamed-chunk-46-1.png){fig-align='center' width=70%}\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nplot_t(df = 17, region = \"right\", value1 = -2.567, \n       title = \"d) P(T > -2.567), v = 17\")\n```\n\n::: {.cell-output-display}\n![](trabajoestadistica2_files/figure-html/unnamed-chunk-47-1.png){fig-align='center' width=70%}\n:::\n:::\n\n\n**Ejercicio 8.49**\n\nDada una muestra aleatoria de tamaño 24 de una distribución normal, encuentre kk tal que:\n\na.  $P(-2.069 < T < k) = 0.965$\nb.  $P(k < T < 2.807) = 0.095$\nc.  $P(-k < T < k) = 0.90$\n\n**Solucion**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nv <- 24 - 1\np_left <- pt(-2.069, df = v)   # Probabilidad acumulada en -2.069\ntarget <- 0.965 + p_left       # Acumulada deseada\nk_a <- qt(target, df = v)\nk_a\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2.499077\n```\n\n\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\np_2807 <- pt(2.807, df = v)\np_k <- p_2807 - 0.095\nk_b <- qt(p_k, df = v)\nk_b\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.319437\n```\n\n\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nk_c <- qt(0.95, df = v)\nk_c\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.713872\n```\n\n\n:::\n:::\n\n\n**Gráficos**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nv <- 23\nk_a <- qt(0.965 + pt(-2.069, df=v), df=v)\nk_b <- qt(1 - 0.095, df=v, lower.tail = TRUE, ncp = 0)\np_upper <- pt(2.807, df=v)\nk_b <- qt(p_upper - 0.095, df=v)\nk_c <- qt(0.95, df=v)\nk_a; k_b; k_c\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2.499077\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.319437\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.713872\n```\n\n\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nx <- seq(-4, 4, length=500)\ndens <- dt(x, df=v)\ndf_plot <- data.frame(x, dens)\nshade_region <- function(a, b, df, title){\n  ggplot(df, aes(x, dens)) +\n    geom_line(color=\"blue\") +\n    geom_area(data=subset(df, x>=a & x<=b),\n              aes(x=x, y=dens), fill=\"skyblue\", alpha=0.5) +\n    labs(title=title, x=\"T\", y=\"Densidad\") +\n    theme_minimal()\n}\nplot_a <- shade_region(-2.069, k_a, df_plot, \"a) P(-2.069 < T < k) = 0.965\")\nplot_b <- shade_region(k_b, 2.807, df_plot, \"b) P(k < T < 2.807) = 0.095\")\nplot_c <- shade_region(-k_c, k_c, df_plot, \"c) P(-k < T < k) = 0.90\")\nplot_a\n```\n\n::: {.cell-output-display}\n![](trabajoestadistica2_files/figure-html/unnamed-chunk-52-1.png){fig-align='center' width=70%}\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nplot_b\n```\n\n::: {.cell-output-display}\n![](trabajoestadistica2_files/figure-html/unnamed-chunk-53-1.png){fig-align='center' width=70%}\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nplot_c\n```\n\n::: {.cell-output-display}\n![](trabajoestadistica2_files/figure-html/unnamed-chunk-54-1.png){fig-align='center' width=70%}\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n<br>\n\n## **Shiny Interactivo Dostribucion t de Student**\n\n```{shinylive-r}\n#| standalone: true\n#| viewerHeight: 550\n\nlibrary(shiny)\nlibrary(ggplot2)\n\nui <- fluidPage(\n  titlePanel(\"Distribución t de Student\"),\n  \n  sidebarLayout(\n    sidebarPanel(\n      h4(\"Parámetros de la Distribución\"),\n      sliderInput(\"t_df\", \"Grados de libertad (v):\", min = 1, max = 100, value = 3, step = 1),\n      checkboxInput(\"show_norm_t\", \"Comparar con Normal Estándar N(0,1)\", FALSE)\n    ),\n    \n    mainPanel(\n      plotOutput(\"dist_plot\", height = \"480px\")\n    )\n  )\n)\n\nserver <- function(input, output) {\n  output$dist_plot <- renderPlot({\n    df_val <- input$t_df\n    \n    g <- ggplot() + \n      theme_minimal() +\n      theme(\n        plot.title = element_text(size = 14, face = \"bold\", hjust = 0.5),\n        axis.title = element_text(size = 11),\n        legend.position = \"bottom\"\n      ) +\n      stat_function(fun = dt, args = list(df = df_val),\n                    linewidth = 1.2, aes(color = \"t de Student\")) +\n      xlim(-4, 4) +\n      labs(title = paste0(\"Distribución t de Student con \", df_val, \" Grados de Libertad\"),\n           x = \"Valores (t)\", y = \"Densidad\", color = \"\")\n      \n    # Comparación con la Normal estándar N(0,1)\n    if (input$show_norm_t) {\n      g <- g + stat_function(fun = dnorm, args = list(mean = 0, sd = 1),\n                             linewidth = 1, linetype = \"dashed\", aes(color = \"Normal Estándar N(0,1)\"))\n      color_map <- c(\"t de Student\" = \"#2980B9\", \"Normal Estándar N(0,1)\" = \"#E74C3C\")\n    } else {\n      color_map <- c(\"t de Student\" = \"#2980B9\")\n    }\n    \n    g <- g + scale_color_manual(values = color_map)\n    print(g)\n  })\n}\n\nshinyApp(ui = ui, server = server)\n```\n\n\n<br>\n\n\n\n# Distribución F de Fisher\n\nLa **distribución F**, también conocida como **F de Fisher-Snedecor**, es una distribución de probabilidad **continua** que surge a partir de la razón entre dos variables aleatorias chi-cuadrado normalizadas por sus grados de libertad.\n\n**Definición formal**\n\nSi:\n\n\\-$X \\sim \\chi_{v_1}^2$ (una chi-cuadrado con $v_1$ grados de libertad),\n\n- $Y \\sim \\chi_{v_2}^2$ (otra chi-cuadrado con $v_2$ grados de libertad), y $X$ y $Y$ son independientes,\n\nentonces la variable:\n\n$$F = \\frac{X / v_1}{Y / v_2}$$\n\nsigue una **distribución F** con $(v_1, v_2)$ grados de libertad.\n\n**Propiedades principales**\n\n1.  **Soporte**: $F > 0$, es decir, solo toma valores positivos.\n\n2.  **Asimétrica**: la curva de densidad es sesgada a la derecha, especialmente para pocos grados de libertad.\n\n3.  **Esperanza matemática**:\n\n$$E(F) = \\frac{v_2}{v_2 - 2} \\quad \\text{para } v_2 > 2$$\n\n4.  **Varianza**:\n\n$$Var(F) = \\frac{2v_2^2(v_1 + v_2 - 2)}{v_1(v_2 - 2)^2(v_2 - 4)} \\quad \\text{para } v_2 > 4$$\n\n5.  Cuando los grados de libertad son grandes, la distribución F tiende a concentrarse cerca de 1.\n\n**Usos más comunes**\n\n1.  **Análisis de Varianza (ANOVA):** se utiliza para contrastar si varias medias poblacionales son iguales.\n\n2.  **Pruebas de hipótesis sobre varianzas:** por ejemplo, para comparar si dos poblaciones tienen varianzas iguales.\n\n3.  **Regresión lineal:** la prueba F sirve para evaluar la significancia global del modelo.\n\n**Familia de Curvas F de Fisher**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nx <- seq(0, 5, length.out = 500)\ndf_combinations <- list(\n  c(1, 5),\n  c(2, 10),\n  c(5, 10),\n  c(10, 20)\n)\ndf <- data.frame()\nfor (df_pair in df_combinations) {\n  v1 <- df_pair[1]\n  v2 <- df_pair[2]\n  dens <- df(x, df1 = v1, df2 = v2) # función de densidad de la distribución F\n  df <- rbind(df, data.frame(x = x, y = dens,\n                             label = paste0(\"v1=\", v1, \", v2=\", v2)))\n}\nggplot(df, aes(x = x, y = y, color = label)) +\n  geom_line(size = 1) +\n  labs(title = \"Familia de curvas de la distribución F\",       x = \"x\",       y = \"Densidad\",\n       color = \"Grados de libertad\") +\n  theme_minimal(base_size = 14)\n```\n\n::: {.cell-output-display}\n![](trabajoestadistica2_files/figure-html/unnamed-chunk-56-1.png){fig-align='center' width=70%}\n:::\n:::\n\n\n**Ejercicio 8.53**\n\nPara una distribución FF encuentre:\n\na.  $f_{0.05}$ con $v_1 = 7$ y $v_2 = 15$\n\nb.  $f_{0.05}$ con $v_1 = 15$ y $v_2 = 7$\n\nc.  $f_{0.01}$ con $v_1 = 24$ y $v_2 = 19$\n\nd.  $f_{0.95}$ con $v_1 = 19$ y $v_2 = 24$\n\ne.  $f_{0.99}$ con $v_1 = 28$ y $v_2 = 12$\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nf_a <- qf(0.05, df1 = 7, df2 = 15)\nf_b <- qf(0.05, df1 = 15, df2 = 7)\nf_c <- qf(0.01, df1 = 24, df2 = 19)\nf_d <- qf(0.95, df1 = 19, df2 = 24)\nf_e <- qf(0.99, df1 = 28, df2 = 12)\nresultados <- data.frame(\n  Inciso = c(\"a\", \"b\", \"c\", \"d\", \"e\"),\n  Valor_F = c(f_a, f_b, f_c, f_d, f_e)\n)\nprint(resultados)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Inciso   Valor_F\n1      a 0.2848402\n2      b 0.3694636\n3      c 0.3620048\n4      d 2.0398575\n5      e 3.7237467\n```\n\n\n:::\n:::\n\n\nGraficas\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nx <- seq(0, 5, length.out = 500)\ndf_combinations <- list(\n  c(1, 5),\n  c(2, 10),\n  c(5, 10),\n  c(10, 20)\n)\ndf_plot <- data.frame()\nfor (df_pair in df_combinations) {\n  v1 <- df_pair[1]\n  v2 <- df_pair[2]\n  dens <- df(x, df1 = v1, df2 = v2)\n  df_plot <- rbind(df_plot, data.frame(x = x, y = dens, label = paste0(\"v1=\", v1, \", v2=\", v2)))\n}\nggplot(df_plot, aes(x = x, y = y, color = label)) +\n  geom_line(size = 1) +\n  labs(title = \"Familia de curvas de la distribución F\", x = \"x\", y = \"Densidad\", color = \"Grados de libertad\") +\n  theme_minimal(base_size = 14)\n```\n\n::: {.cell-output-display}\n![](trabajoestadistica2_files/figure-html/unnamed-chunk-58-1.png){fig-align='center' width=70%}\n:::\n:::\n\n\n<br>\n\n## **Shiny Interactivo Dostribucion F de Fisher**\n\n\n```{shinylive-r}\n#| standalone: true\n#| viewerHeight: 550\n\nlibrary(shiny)\nlibrary(ggplot2)\n\nui <- fluidPage(\n  titlePanel(\"Distribución F de Fisher\"),\n  \n  sidebarLayout(\n    sidebarPanel(\n      h4(\"Parámetros de la Distribución\"),\n      sliderInput(\"f_df1\", \"Grados de libertad del numerador (d1):\", min = 1, max = 100, value = 5, step = 1),\n      sliderInput(\"f_df2\", \"Grados de libertad del denominador (d2):\", min = 1, max = 100, value = 10, step = 1)\n    ),\n    \n    mainPanel(\n      plotOutput(\"dist_plot\", height = \"480px\")\n    )\n  )\n)\n\nserver <- function(input, output) {\n  output$dist_plot <- renderPlot({\n    df1 <- input$f_df1\n    df2 <- input$f_df2\n    \n    g <- ggplot() + \n      theme_minimal() +\n      theme(\n        plot.title = element_text(size = 14, face = \"bold\", hjust = 0.5),\n        axis.title = element_text(size = 11),\n        legend.position = \"bottom\"\n      ) +\n      stat_function(fun = df, args = list(df1 = df1, df2 = df2),\n                    linewidth = 1.2, aes(color = \"F de Fisher\")) +\n      xlim(0, 4) +\n      scale_color_manual(values = c(\"F de Fisher\" = \"#27AE60\")) +\n      labs(title = paste0(\"Distribución F de Fisher (d1 = \", df1, \", d2 = \", df2, \")\"),\n           x = \"Valores (F)\", y = \"Densidad\", color = \"\")\n    \n    print(g)\n  })\n}\n\nshinyApp(ui = ui, server = server)\n```\n\n\n<br>\n\n\n# Teorema del limite central\n\nEl **Teorema del Límite Central** (TLC) es uno de los conceptos más importantes en estadística. En términos simples, establece que la **distribución de la media de una muestra** se aproxima a una **distribución normal** a medida que el tamaño de la muestra aumenta, sin importar la forma de la distribución original de la población.\n\n**Concepto y Analogía**\n\nImagina que tienes una población con una distribución extraña, por ejemplo, muy sesgada. Si tomas una sola muestra grande de esa población y calculas su media, esa media se comportará de manera predecible. Si repites este proceso muchas veces, las medias de todas esas muestras formarán un histograma que se parecerá cada vez más a una curva de campana (la distribución normal).\n\nUna analogía popular es la de los dados. La distribución de probabilidad de un solo dado es uniforme (cada número tiene la misma probabilidad). Sin embargo, si lanzas muchos dados y sumas sus resultados, la distribución de esas sumas se aproximará a una campana, con los resultados centrales (la media) siendo mucho más probables que los extremos.\n\n**Puntos Clave del Teorema**\n\n1.  **Forma de la Distribución de Muestreo**: La distribución de las medias de la muestra se vuelve normal, sin importar si la población original era normal, sesgada, uniforme o de cualquier otra forma.\n\n2.  **Tamaño de la Muestra (n)**: La aproximación a la normalidad es más precisa a medida que el tamaño de la muestra $(n)$ aumenta. Generalmente, una muestra de$n \\ge 30$ es considerada suficiente para que la aproximación sea válida.\n\n3.  **Relación con la Media de la Población**: La media de la distribución de muestreo de las medias $\\mu_{\\bar{x}}$es igual a la media de la población $\\mu$\n\n    $$\\mu_{\\bar{x}} = \\mu$$\n\n4.  **Relación con la Desviación Estándar de la Población**: La desviación estándar de la distribución de muestreo de las medias, llamada **error estándar** $\\sigma_{\\bar{x}}$, es igual a la desviación estándar de la población ($\\sigma$) dividida por la raíz cuadrada del tamaño de la muestra\n\n    $$\\sigma_{\\bar{x}} = \\frac{\\sigma}{\\sqrt{n}}$$\n\n    Esto significa que, a medida que el tamaño de la muestra aumenta, el error estándar disminuye, y las medias de las muestras se agrupan más estrechamente alrededor de la media de la población.\n\n**Importancia**\n\nEl Teorema del Límite Central es fundamental porque permite utilizar la **distribución normal** (que es fácil de trabajar) para hacer inferencias sobre la media de la población, incluso cuando no se conoce la distribución de la población original. Esto es la base para muchas pruebas estadísticas, como los intervalos de confianza y las pruebas de hipótesis.\n\n**Simulacion para la distribucion binomial**\n\n**Distribucion binomial original**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nk <- 10      # Número de ensayos de la binomial\np <- 0.35    # Probabilidad de éxito\npoblacion <- data.frame(x = 0:k,probabilidad = dbinom(0:k, size = k, prob = p))\nggplot(poblacion, aes(x = x, y = probabilidad)) +\n  geom_bar(stat = \"identity\", fill = \"#91cc02\", alpha = 0.8) +\n  labs( title = \"Distribución Binomial Original\",   x = \"Número de Éxitos\",    y = \"Probabilidad\" ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](trabajoestadistica2_files/figure-html/unnamed-chunk-59-1.png){fig-align='center' width=70%}\n:::\n:::\n\n\n**Distribución de las medias muestrales**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(123)\nk <- 10      # Número de ensayos de la binomial\np <- 0.35    # Probabilidad de éxito\nn <- 30      # Tamaño de la muestra\nR <- 10000   # Número de repeticiones\nmedias_muestrales <- replicate(R, {\n  muestra <- rbinom(n, size = k, prob = p)\n  mean(muestra)\n})\ndf_medias <- data.frame(media = medias_muestrales)\nggplot(df_medias, aes(x = media)) +\n  geom_histogram(aes(y = after_stat(density)), bins = 30, fill = \"#91cc02\", color = \"white\", alpha = 0.8) +\n  stat_function(fun = dnorm, args = list(mean = mean(df_medias$media), sd = sd(df_medias$media)), color = \"darkblue\", size = 1.5, linetype = \"dashed\") +\n  labs(  title = \"Distribución de las Medias Muestrales\",  x = \"Media de la Muestra\",  y = \"Densidad\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](trabajoestadistica2_files/figure-html/unnamed-chunk-60-1.png){fig-align='center' width=70%}\n:::\n:::\n\n\n**Simulacion para la distribucion de Poisson**\n\n**Distribucion de Poisson original**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(123)\nlambda <- 3.5\noriginal_dist <- data.frame(  x = 0:15,  probability = dpois(0:15, lambda = lambda))\nggplot(original_dist, aes(x = x, y = probability)) +\n  geom_bar(stat = \"identity\", fill = \"#fd1ebc\", width = 0.5) +\n  labs(   title = \"Distribucion de Poisson origianal\", x = \"Number of Events\",  y = \"Probability\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](trabajoestadistica2_files/figure-html/unnamed-chunk-61-1.png){fig-align='center' width=70%}\n:::\n:::\n\n\n**Distribución de las medias muestrales**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nn <- 30 \nR <- 10000 \nsample_means <- replicate(R, {\n  sample_data <- rpois(n, lambda = lambda)\n  mean(sample_data)\n})\ndf_sample_means <- data.frame(mean = sample_means)\nggplot(df_sample_means, aes(x = mean)) +\n  geom_histogram(aes(y = after_stat(density)), bins = 30, fill = \"#fd1ebc\", color = \"white\", alpha = 0.8) +\n  stat_function(fun = dnorm, args = list(mean = mean(df_sample_means$mean), sd = sd(df_sample_means$mean)), color = \"darkblue\", size = 1.2, linetype = \"dashed\") +\n  labs(  title = \"Distribución de las Medias Muestrales\",  x = \"Sample Mean\", y = \"Density\" ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](trabajoestadistica2_files/figure-html/unnamed-chunk-62-1.png){fig-align='center' width=70%}\n:::\n:::\n\n\n**Simulacion para la distribucion Hipergeometrica**\n\n**Distribucion Hipergeometrica original**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nN <- 1000  # Tamaño de la población\nK <- 350   # Número de éxitos en la población\nn <- 30    # Tamaño de la muestra\noriginal_dist <- data.frame( exitos = 0:n, probabilidad = dhyper(x = 0:n, m = K, n = N - K, k = n)\n)\nggplot(original_dist, aes(x = exitos, y = probabilidad)) +\n  geom_bar(stat = \"identity\", fill = \"#8d8dad\", width = 0.5) +\n  labs(    title = \"Distribución Hipergeométrica Original\",   x = \"Número de Éxitos en la Muestra\",    y = \"Probabilidad\"  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](trabajoestadistica2_files/figure-html/unnamed-chunk-63-1.png){fig-align='center' width=70%}\n:::\n:::\n\n\n**Distribución de las medias muestrales**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(123)\nn <- 30      # Tamaño de la muestra\nR <- 10000   # Número de repeticiones\nmedias_muestrales <- replicate(R, {\n  exitos_muestra <- rhyper(nn = 1, m = K, n = N - K, k = n)\n  exitos_muestra / n\n})\ndf_medias <- data.frame(media = medias_muestrales)\nggplot(df_medias, aes(x = media)) +\n  geom_histogram(aes(y = after_stat(density)), bins = 30, fill = \"#8d8dad\", color = \"white\", alpha = 0.8) +\n  stat_function(fun = dnorm, args = list(mean = mean(df_medias$media), sd = sd(df_medias$media)), color = \"darkblue\", size = 1.2, linetype = \"dashed\") +\n  labs(  title = \"Distribución de las Medias Muestrales\",   x = \"Media de la Muestra\",  y = \"Densidad\"  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](trabajoestadistica2_files/figure-html/unnamed-chunk-64-1.png){fig-align='center' width=70%}\n:::\n:::\n\n\n<br>\n\n## **Shiny Interactivo para el Teorema Central del Limite (TCL)**\n\n```{shinylive-r}\n#| standalone: true\n#| viewerHeight: 500\n\nlibrary(shiny)\nlibrary(ggplot2)\nlibrary(gridExtra)\n\nui <- fluidPage(\n  titlePanel(\"Simulación del Teorema Central del Límite (TCL)\"),\n  \n  sidebarLayout(\n    sidebarPanel(\n      selectInput(\"dist\", \"Distribución:\",\n                  choices = c(\"Uniforme\", \"Binomial\", \"Poisson\",\n                              \"Hipergeométrica\", \"Exponencial\")),\n      \n      # Parámetros dinámicos\n      conditionalPanel(\n        condition = \"input.dist == 'Uniforme'\",\n        numericInput(\"a\", \"Mínimo (a):\", 0),\n        numericInput(\"b\", \"Máximo (b):\", 1)\n      ),\n      \n      conditionalPanel(\n        condition = \"input.dist == 'Binomial'\",\n        numericInput(\"size\", \"Ensayos (n):\", 10, min = 1),\n        sliderInput(\"p\", \"Probabilidad (p):\", value = 0.3, min = 0, max = 1, step = 0.01)\n      ),\n      \n      conditionalPanel(\n        condition = \"input.dist == 'Poisson'\",\n        numericInput(\"lambda_pois\", \"Lambda:\", 4, min = 0.1)\n      ),\n      \n      conditionalPanel(\n        condition = \"input.dist == 'Hipergeométrica'\",\n        numericInput(\"Npop\", \"Tamaño población (N):\", 1000, min = 10),\n        numericInput(\"K\", \"Éxitos en población (K):\", 300, min = 1),\n        numericInput(\"m\", \"Tamaño de muestra (m):\", 20, min = 1)\n      ),\n      \n      conditionalPanel(\n        condition = \"input.dist == 'Exponencial'\",\n        numericInput(\"lambda_exp\", \"Lambda:\", 1.5, min = 0.1)\n      ),\n      \n      hr(),\n      \n      numericInput(\"n\", \"Tamaño de muestra (TCL):\", 30, min = 1),\n      numericInput(\"Nsim\", \"Número de simulaciones:\", 10000, min = 1000),\n      \n      actionButton(\"simular\", \"Simular\")\n    ),\n    \n    mainPanel(\n      plotOutput(\"plots\", height = \"450px\")\n    )\n  )\n)\n\nserver <- function(input, output) {\n  \n  sim_data <- eventReactive(input$simular, {\n    \n    set.seed(123)\n    \n    N <- 100000\n    \n    # --------------------------\n    # GENERAR SEGÚN DISTRIBUCIÓN\n    # --------------------------\n    \n    if (input$dist == \"Uniforme\") {\n      poblacion <- runif(N, input$a, input$b)\n      medias <- replicate(input$Nsim,\n                          mean(runif(input$n, input$a, input$b)))\n      \n      mu <- (input$a + input$b)/2\n      sigma <- (input$b - input$a)/sqrt(12)\n    }\n    \n    else if (input$dist == \"Binomial\") {\n      poblacion <- rbinom(N, input$size, input$p)\n      medias <- replicate(input$Nsim,\n                          mean(rbinom(input$n, input$size, input$p)))\n      \n      mu <- input$size * input$p\n      sigma <- sqrt(input$size * input$p * (1 - input$p))\n    }\n    \n    else if (input$dist == \"Poisson\") {\n      poblacion <- rpois(N, input$lambda_pois)\n      medias <- replicate(input$Nsim,\n                          mean(rpois(input$n, input$lambda_pois)))\n      \n      mu <- input$lambda_pois\n      sigma <- sqrt(input$lambda_pois)\n    }\n    \n    else if (input$dist == \"Hipergeométrica\") {\n      poblacion <- rhyper(N,\n                          m = input$K,\n                          n = input$Npop - input$K,\n                          k = input$m)\n      \n      medias <- replicate(input$Nsim,\n                          mean(rhyper(input$n,\n                                      m = input$K,\n                                      n = input$Npop - input$K,\n                                      k = input$m)))\n      \n      mu <- input$m * (input$K / input$Npop)\n      sigma <- sqrt(input$m * (input$K / input$Npop) *\n                      (1 - input$K / input$Npop) *\n                      ((input$Npop - input$m)/(input$Npop - 1)))\n    }\n    \n    else if (input$dist == \"Exponencial\") {\n      poblacion <- rexp(N, input$lambda_exp)\n      medias <- replicate(input$Nsim,\n                          mean(rexp(input$n, input$lambda_exp)))\n      \n      mu <- 1 / input$lambda_exp\n      sigma <- 1 / input$lambda_exp\n    }\n    \n    list(poblacion = poblacion,\n         medias = medias,\n         mu = mu,\n         sigma = sigma)\n  })\n  \n  output$plots <- renderPlot({\n    \n    data <- sim_data()\n    \n    df_pob <- data.frame(x = data$poblacion)\n    df_med <- data.frame(x = data$medias)\n    \n    # Gráfico población\n    g1 <- ggplot(df_pob, aes(x = x)) +\n      geom_histogram(aes(y = ..density..),\n                     bins = 50,\n                     fill = \"lightgreen\",\n                     color = \"black\") +\n      stat_function(fun = dnorm,\n                    args = list(mean = data$mu,\n                                sd = data$sigma),\n                    color = \"darkgreen\",\n                    linewidth = 1) +\n      labs(title = \"Población\",\n           x = \"Valores\",\n           y = \"Densidad\") +\n      theme_minimal()\n    \n    # Gráfico TCL\n    g2 <- ggplot(df_med, aes(x = x)) +\n      geom_histogram(aes(y = ..density..),\n                     bins = 30,\n                     fill = \"lightblue\",\n                     color = \"black\") +\n      stat_function(fun = dnorm,\n                    args = list(mean = data$mu,\n                                sd = data$sigma/sqrt(input$n)),\n                    color = \"red\",\n                    linewidth = 1.2) +\n      labs(title = \"Distribución muestral de la media\",\n           x = \"Media muestral\",\n           y = \"Densidad\") +\n      theme_minimal()\n    \n    grid.arrange(g1, g2, ncol = 2)\n  })\n}\n\nshinyApp(ui = ui, server = server)\n```\n\n\n",
    "supporting": [
      "trabajoestadistica2_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}