{
  "hash": "f4d4a454429563d2f4aa48311c95d7ca",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"MODELOS CONTINUOS Y TLC\"\nsubtitle: \"SHINYS INTERACTIVOS\"\nauthor: \n  - name: Mauricio Borda<br>Johan Rodriguez<br>Alannis Duque\n    affiliation: \"Universidad del Tolima\"\n    affiliation-url: \"https://www.ut.edu.co/\"\ndate: today\nlang: es\nbibliography: referencias.bib\nlink-citations: true\nnocite: |\n  @*\ntitle-block-banner: \"#5f17a3\"\nfilters:\n  - shinylive\nformat:\n  html:\n    page-layout: full\n    fontsize: 14pt\n    toc: true\n    toc-location: right\n\n    number-sections: true\n    code-fold: true\n    code-summary: \"Ver código\"\n    theme: dark\n    highlight-style: monokai\n    html-math-method: katex\n    smooth-scroll: true\n    link-external-newwindow: true\n    code-overflow: scroll\n    favicon: favicon.ico\neditor: visual\n\nknitr:\n  opts_chunk:\n    message: false\n    warning: false\n    fig.align: center\n    fig.width: 6\n    fig.height: 6\n    out.width: \"70%\"\n---\n\n```{=html}\n<div style=\"position:absolute; top:10px; right:10px;\">\n<img src=\"ut.png\" width=\"150\">\n</div>\n```\n\n```{=html}\n<style>\nbody{\n  background-color:#ffffff;\n  font-size:130%;\n  text-align:justify;\n}\n</style>\n```\n\n# Cargar paquetes\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nipak <- function(pkg){\n\n  options(repos = c(CRAN=\"https://cloud.r-project.org\"))\n\n  new.pkg <- pkg[!(pkg %in% rownames(installed.packages()))]\n\n  if(length(new.pkg)) install.packages(new.pkg, dependencies = TRUE)\n\n  invisible(lapply(pkg, function(p)\n    suppressPackageStartupMessages(library(p, character.only = TRUE))\n  ))\n}\n\npackages <- c(\"tidyverse\",\"kableExtra\",\"psych\",\"readxl\")\n\nipak(packages)\n```\n:::\n\n\n# Distribucion Normal\n\nLa distribución normal, también conocida como distribución gaussiana o campana de Gauss, es la distribución de probabilidad continua más importante en la estadística.\n\nSu importancia radica en que muchos fenómenos naturales, sociales y económicos siguen este patrón.\n\nLa distribución normal es la distribución de probabilidad continua más usada en estadística y una herramienta fundamental para modelar una inmensa variedad de fenómenos en las ciencias, la ingeniería y la economía. Su popularidad se debe a una propiedad matemática conocida como el Teorema del Límite Central, que establece que la suma o el promedio de un gran número de variables aleatorias independientes (sin importar su distribución original) tiende a seguir una distribución normal.\n\n## Características Clave {.unnumbered}\n\nLa distribución normal es un tipo de distribución de probabilidad continua. Esto significa que la variable aleatoria puede tomar cualquier valor dentro de un rango determinado. Se representa por una curva simétrica en forma de campana, donde la mayor parte de los datos se agrupan alrededor del valor central.\n\n**Forma de Campana:** La distribución es simétrica alrededor de su media, creando una curva con forma de campana. El punto más alto de la campana es la media.\n\n**Media, Mediana y Moda Coincidentes:** En una distribución normal perfecta, estos tres valores son iguales y se encuentran en el centro de la curva.\n\n**Asintótica al Eje Horizontal:** La curva se extiende indefinidamente en ambas direcciones, acercándose al eje x pero sin llegar a tocarlo.\n\n**Regla Empírica:** Alrededor del 68% de los datos se encuentran dentro de una desviación estándar de la media (μ±σ), el 95% dentro de dos desviaciones estándar (μ±2σ), y el 99.7% dentro de tres desviaciones estándar (μ±3σ).\n\n- **Parámetros**\n\nLa distribución normal está completamente definida por dos parámetros:\n\n**Media (μ):** Indica la ubicación del centro de la curva y el valor más probable.\n\n**Varianza σ2σ2 o Desviación Estándar (σ):** Mide la dispersión o variabilidad de los datos. Una σ grande resulta en una curva más ancha y aplanada, mientras que una σ pequeña crea una curva más estrecha y alta.\n\n- **Fórmulas**\n\nLa fórmula principal de la distribución normal es la función de densidad de probabilidad (FDP). Esta función no calcula la probabilidad de un punto exacto, sino la densidad de probabilidad en ese punto.\n\nFunción de Densidad de Probabilidad (FDP):\n\n$$f(x)=σ2π\n​1​e−21​(σx−μ​)2$$\n\nDonde:\n\n**x** es el valor de la variable aleatoria.\n\n**μ** es la media.\n\n**σ** es la desviación estándar.\n\n**e** es el número de Euler (aproximadamente 2.71828).\n\n**π** es la constante pi (aproximadamente 3.14159).\n\nPara calcular probabilidades, se utiliza la distribución normal estándar, que tiene una media de 0 y una desviación estándar de 1. Cualquier variable normal puede estandarizarse usando la siguiente fórmula:\n\n**Formula de Estandarización (puntuación Z):**\n\n$$Z=x−μσ\nZ=σx−μ​$$\n\nLa puntuación Z nos dice cuántas desviaciones estándar está un valor dado de la media. Luego, se usan tablas o software estadístico para encontrar las probabilidades correspondientes.\n\n<br>\n\n## Ejercicios\n\n## Ejercicio 6.7 {.unnumbered}\n\nUn investigador cientíﬁco informa que unos ratones vivirán un promedio de 40 meses cuando sus dietas se restringen drásticamente y después se enriquecen con vitaminas y proteínas. Suponiendo que la vidas de tales ratones se distribuyen normalmente con una desviación estándar de 6.3 meses, encuentre la probabilidad de que un ratón dado vivirá:\n\n**a)** más de 32 meses<br>**b)** menos de 28 meses<br>**c)** entre 37 y 49 meses\n\n- **Parametros**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmedia <- 40 \ndesviacion_estandar <- 6.3 \n```\n:::\n\n\n### Solución a los incisos\n\n::: panel-tabset\n#### Inciso A\n\nCual es probabilidad de que un ratón dado vivirá más de 32 meses.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nprob_mas_de_32 <- 1 - pnorm(32, mean = media, sd = desviacion_estandar)\ncat(\"a)\", round(prob_mas_de_32, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\na) 0.8979 \n```\n\n\n:::\n:::\n\n\nLa probabilidad de que un ratón viva más de 32 meses es 0.8979.\n\n**Grafica**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmedia <- 40\ndesviacion_estandar <- 6.3\nrango <- c(media - 3 * desviacion_estandar, media + 3 * desviacion_estandar)\nggplot(data.frame(x = rango), aes(x = x)) +  # Curva de la distribución normal\n  stat_function(fun = dnorm, args = list(mean = media, sd = desviacion_estandar), \n                n = 500, color = \"black\") +  # Resaltar el área de interés (X > 32)\n  geom_area(stat = \"function\", fun = dnorm, args = list(mean = media, sd = desviacion_estandar),\n            fill = \"steelblue\", xlim = c(32, rango[2]), alpha = 0.5) +  # Etiquetas y títulos\n  labs(    title = \"Distribucion Normal\",    subtitle = \"Probabilidad de vivir más de 32 meses\",    x = \"Vida en meses\",    y = \"Densidad de Probabilidad\"  ) +  theme_bw() +  # Línea para el valor de 32\n  geom_vline(xintercept = 32, linetype = \"dashed\", color = \"red\") +\n  geom_text(aes(x = 32, y = 0.01, label = \"32 meses\"), hjust = -0.1, vjust = -1)\n```\n\n::: {.cell-output-display}\n![](trabajoestadis_files/figure-html/unnamed-chunk-4-1.png){fig-align='center' width=70%}\n:::\n:::\n\n\nLa probabilidad de que un ratón viva más de 32 meses es 89.79%\n\n#### Inciso B\n\nCual es la probabilidad de que un ratón dado vivirá más de 28 meses.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nprob_menos_de_28 <- pnorm(28, mean = media, sd = desviacion_estandar)\ncat(\"b)\", round(prob_menos_de_28, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nb) 0.0284 \n```\n\n\n:::\n:::\n\n\nLa probabilidad de que un ratón viva más de 32 meses es 0.0284.\n\n**Grafica**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmedia <- 40\ndesviacion_estandar <- 6.3\nrango <- c(media - 3 * desviacion_estandar, media + 3 * desviacion_estandar)\nggplot(data.frame(x = rango), aes(x = x)) +  # Curva de la distribución normal\n  stat_function(fun = dnorm, args = list(mean = media, sd = desviacion_estandar), \n                n = 500, color = \"black\") +  # Resaltar el área de interés (X < 28)\n  geom_area(stat = \"function\", fun = dnorm, args = list(mean = media, sd = desviacion_estandar),\n            fill = \"orange\", xlim = c(rango[1], 28), alpha = 0.5) +  # Etiquetas y títulos\n  labs(    title = \"Distribucion Normal\",    subtitle = \"Probabilidad de vivir menos de 28 meses\",    x = \"Vida en meses\",    y = \"Densidad de Probabilidad\"  ) +  theme_bw() +  # Línea para el valor de 28\n  geom_vline(xintercept = 28, linetype = \"dashed\", color = \"red\") +\n  geom_text(aes(x = 28, y = 0.01, label = \"28 meses\"), hjust = 1.1, vjust = -1)\n```\n\n::: {.cell-output-display}\n![](trabajoestadis_files/figure-html/unnamed-chunk-6-1.png){fig-align='center' width=70%}\n:::\n:::\n\n\nLa probabilidad de que un ratón viva más de 32 meses es 2.84%.\n\n#### Inciso C\n\nCual es la probabilidad de que un ratón dado vivirá más de 49 meses.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nprob_c_superior <- pnorm(49, mean = media, sd = desviacion_estandar)\nprob_c_inferior <- pnorm(37, mean = media, sd = desviacion_estandar)\nprob_c <- prob_c_superior - prob_c_inferior\ncat(\"c)\", round(prob_c, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nc) 0.6065 \n```\n\n\n:::\n:::\n\n\nLa probabilidad de que un ratón viva más de 32 meses es 0.6065.\n\n**Grafica**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmedia <- 40\ndesviacion_estandar <- 6.3\nrango <- c(media - 3 * desviacion_estandar, media + 3 * desviacion_estandar)\nggplot(data.frame(x = rango), aes(x = x)) +  # Curva de la distribución normal\n  stat_function(fun = dnorm, args = list(mean = media, sd = desviacion_estandar), \n                n = 500, color = \"black\") +  # Resaltar el área de interés (37 < X < 49)\n  geom_area(stat = \"function\", fun = dnorm, args = list(mean = media, sd = desviacion_estandar),\n            fill = \"purple\", xlim = c(37, 49), alpha = 0.5) +  # Etiquetas y títulos\n  labs(    title = \"Distribucion Normal\",    subtitle = \"Probabilidad de vivir entre 37 y 49 meses\",    x = \"Vida en meses\",    y = \"Densidad de Probabilidad\"  ) +  theme_bw() +  # Líneas para los valores de 37 y 49\n  geom_vline(xintercept = 37, linetype = \"dashed\", color = \"red\") +\n  geom_vline(xintercept = 49, linetype = \"dashed\", color = \"red\") +\n  geom_text(aes(x = 37, y = 0.01, label = \"37\"), hjust = 1.1, vjust = -1) +\n  geom_text(aes(x = 49, y = 0.01, label = \"49\"), hjust = -0.1, vjust = -1)\n```\n\n::: {.cell-output-display}\n![](trabajoestadis_files/figure-html/unnamed-chunk-8-1.png){fig-align='center' width=70%}\n:::\n:::\n\n\nLa probabilidad de que un ratón viva más de 32 meses es 60.65%.\n:::\n\n<br>\n\n## Ejercicio 6.9 {.unnumbered}\n\nUna máquina expendedora de bebidas gaseosas se regula para que sirva un promedio de 200 mililitros por vaso. Si la cantidad de bebida se distribuye normalmente con una desviación estándar igual a 15 mililitros,\n\n**a)** ¿qué fracción de los vasos contendrá más de 224 mililitros?<br>**b)** ¿cuál es la probabilidad de que un vaso contenga entre 191 y 209 mililitros?<br>**c)** ¿cuántos vasos probablemente se derramarán si se utilizan vasos de 230 mililitros para las siguientes 1000 bebidas?\n\n- **Parametros**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmedia <- 200\ndesviacion_estandar <- 15\n```\n:::\n\n\n### Solución a los incisos\n\n::: panel-tabset\n#### Inciso A\n\n¿Qué fracción de los vasos contendrá más de 224 mililitros?\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nprob_a <- 1 - pnorm(224, mean = media, sd = desviacion_estandar)\ncat(\"a)\", round(prob_a, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\na) 0.0548 \n```\n\n\n:::\n:::\n\n\nLa probabilidad de que una fraccion de vasos contendrá más de 224 mililitros es 0.0548\n\n**Grafica**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nrango <- c(media - 3 * desviacion_estandar, media + 3 * desviacion_estandar)\nggplot(data.frame(x = rango), aes(x = x)) +\n  stat_function(fun = dnorm, args = list(mean = media, sd = desviacion_estandar)) +\n  geom_area(stat = \"function\", fun = dnorm, args = list(mean = media, sd = desviacion_estandar),\n            fill = \"coral\", xlim = c(224, max(rango)), alpha = 0.6) +\n  labs(    title = \"Probabilidad de que un vaso contenga más de 224 ml\",    x = \"Cantidad de bebida (ml)\",    y = \"Densidad de probabilidad\"  ) +\n  geom_vline(xintercept = 224, linetype = \"dashed\", color = \"red\") +  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](trabajoestadis_files/figure-html/unnamed-chunk-11-1.png){fig-align='center' width=70%}\n:::\n:::\n\n\nLa probabilidad de que una fraccion de vasos contendrá más de 224 mililitros es 54.8%.\n\n#### Inciso B\n\n¿Cuál es la probabilidad de que un vaso contenga entre 191 y 209 mililitros?\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmedia <- 200\ndesviacion_estandar <- 15\nprob_b_superior <- pnorm(209, mean = media, sd = desviacion_estandar)\nprob_b_inferior <- pnorm(191, mean = media, sd = desviacion_estandar)\nprob_b <- prob_b_superior - prob_b_inferior\ncat(\"b)\", round(prob_b, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nb) 0.4515 \n```\n\n\n:::\n:::\n\n\nLa probabilidad de que un vaso contenga entre 191 y 209 mililitros es de 0.4515.\n\n**Grafica**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nrango <- c(media - 3 * desviacion_estandar, media + 3 * desviacion_estandar)\nggplot(data.frame(x = rango), aes(x = x)) +\n  stat_function(fun = dnorm, args = list(mean = media, sd = desviacion_estandar)) +\n  geom_area(stat = \"function\", fun = dnorm, args = list(mean = media, sd = desviacion_estandar),\n            fill = \"darkgreen\", xlim = c(191, 209), alpha = 0.6) +\n  labs(    title = \"Probabilidad de un vaso entre 191 ml y 209 ml\",    x = \"Cantidad de bebida (ml)\",    y = \"Densidad de probabilidad\"  ) +\n  geom_vline(xintercept = 191, linetype = \"dashed\", color = \"red\") +\n  geom_vline(xintercept = 209, linetype = \"dashed\", color = \"red\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](trabajoestadis_files/figure-html/unnamed-chunk-13-1.png){fig-align='center' width=70%}\n:::\n:::\n\n\nLa probabilidad de que un vaso contenga entre 191 y 209 mililitros es de 45.15%.\n\n#### Inciso C\n\n¿Cuántos vasos probablemente se derramarán si se utilizan vasos de 230 mililitros para las siguientes 1000 bebidas?\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmedia <- 200\ndesviacion_estandar <- 15\ntotal_vasos <- 1000\nprob_derramarse <- 1 - pnorm(230, mean = media, sd = desviacion_estandar)\nvasos_derramados <- prob_derramarse * total_vasos\ncat(\"c)\", round(vasos_derramados), \"vasos\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nc) 23 vasos\n```\n\n\n:::\n:::\n\n\nSi se utilizan vasos de 230 mililitros para las siguientes 1000 bebidas probablemente se derramarán 23 vasos.\n\n**Grafica**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nrango <- c(media - 3 * desviacion_estandar, media + 3 * desviacion_estandar)\nggplot(data.frame(x = rango), aes(x = x)) +\n  stat_function(fun = dnorm, args = list(mean = media, sd = desviacion_estandar)) +\n  geom_area(stat = \"function\", fun = dnorm, args = list(mean = media, sd = desviacion_estandar),\n            fill = \"purple\", xlim = c(230, max(rango)), alpha = 0.6) +\n  labs(    title = \"Probabilidad de que un vaso se derrame\",    x = \"Cantidad de bebida (ml)\",    y = \"Densidad de probabilidad\"  ) +\n  geom_vline(xintercept = 230, linetype = \"dashed\", color = \"red\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](trabajoestadis_files/figure-html/unnamed-chunk-15-1.png){fig-align='center' width=70%}\n:::\n:::\n\n\nSi se utilizan vasos de 230 mililitros para las siguientes 1000 bebidas probablemente se derramarán 23 vasos.\n:::\n\n<br>\n\n## Ejercicio 6.11 {.unnumbered}\n\nUn abogado viaja todos los días de su casa en los suburbios a su oﬁ cina en el centro de la ciudad. El tiempo promedio para un viaje sólo de ida es 24 minutos, con una desviación estándar de 3.8 minutos. Suponga que la distribución de los tiempos de viaje está distribuida normalmente.\n\n**a)** ¿Cuál es la probabilidad de que un viaje tome al menos 1/2 hora?<br> **b)** Si la oﬁcina abre a las 9:00 A.M. y él sale diario de su casa a las 8:45 A.M., ¿qué porcentaje de las veces llegará tarde al trabajo?<br>**c)** Si sale de su casa a las 8:35 A.M. y el café se sirve en la oﬁcina de 8:50 A.M. a 9:00 A.M., cuál es la probabilidad de que se pierda el café?<br>**d)** Encuentre la longitud de tiempo por arriba de la cual encontramos e1 15% de los viajes más lentos.<br>**e)** Encuentre la probabilidad de que 2 de los siguientes 3 viajes tomen al menos 1/2 hora.<br>\n\n- **Parametros**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmedia <- 24\ndesviacion <- 3.8\n```\n:::\n\n\n### Solución a los incisos\n\n:::: panel-tabset\n#### Inciso A\n\n¿Cuál es la probabilidad de que un viaje tome al menos 1/2 hora?\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmedia <- 24\ndesviacion <- 3.8\nprob_a <- 1 - pnorm(30, mean = media, sd = desviacion)\ncat(\"a)\", round(prob_a, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\na) 0.0572 \n```\n\n\n:::\n:::\n\n\nLa probabilidad de que un viaje tome al menos 1/2 hora es de 0.0572.\n\n**Grafica**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nrango <- c(media - 3 * desviacion, media + 3 * desviacion)\nggplot(data.frame(x = rango), aes(x = x)) +\n  stat_function(fun = dnorm, args = list(mean = media, sd = desviacion), n = 500) +\n  geom_area(stat = \"function\", fun = dnorm, args = list(mean = media, sd = desviacion), fill = \"coral\", xlim = c(30, max(rango)), alpha = 0.6) +\n  labs(title = \"Distribucion Normal\", x = \"Tiempo de viaje (minutos)\", y = \"Densidad de Probabilidad\") +\n  geom_vline(xintercept = 30, linetype = \"dashed\", color = \"red\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](trabajoestadis_files/figure-html/unnamed-chunk-18-1.png){fig-align='center' width=70%}\n:::\n:::\n\n\nLa probabilidad de que un viaje tome al menos 1/2 hora es de 5.72%.\n\n#### Inciso B\n\nSi la oﬁcina abre a las 9:00 A.M. y él sale diario de su casa a las 8:45 A.M., ¿qué porcentaje de las veces llegará tarde al trabajo?\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nprob_b <- 1 - pnorm(15, mean = media, sd = desviacion)\nporcentaje_b <- prob_b * 100\ncat(\"b)\", round(porcentaje_b, 2), \"%\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nb) 99.11 %\n```\n\n\n:::\n:::\n\n\nSi la oﬁcina abre a las 9:00 A.M. y él sale diario de su casa a las 8:45 A.M. 99.11 %xxx llegará tarde al trabajo.\n\n**Grafica**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nrango <- c(media - 3 * desviacion, media + 3 * desviacion)\nggplot(data.frame(x = rango), aes(x = x)) +\n  stat_function(fun = dnorm, args = list(mean = media, sd = desviacion), n = 500) +\n  geom_area(stat = \"function\", fun = dnorm, args = list(mean = media, sd = desviacion),fill = \"#3de3c2\", xlim = c(15, max(rango)), alpha = 0.6) +\n  labs(title = \"Distribucion Normal\", x = \"Tiempo de viaje (minutos)\", y = \"Densidad de Probabilidad\") +\n  geom_vline(xintercept = 15, linetype = \"dashed\", color = \"red\") +  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](trabajoestadis_files/figure-html/unnamed-chunk-20-1.png){fig-align='center' width=70%}\n:::\n:::\n\n\nSi la oﬁcina abre a las 9:00 A.M. y él sale diario de su casa a las 8:45 A.M. 99.11 % llegará tarde al trabajo.\n\n#### Inciso C\n\nSi sale de su casa a las 8:35 A.M. y el café se sirve en la oﬁcina de 8:50 A.M. a 9:00 A.M., cuál es la probabilidad de que se pierda el café?\n\n::: callout-warning\n## Advertencia\n\nEste inciso es un problema de distribución binomial, no normal, ya que se trata de un número discreto de “éxitos” (viajes de más de 30 minutos) en un número fijo de intentos (3 viajes). Por lo tanto, la gráfica no es una curva de densidad normal, sino un gráfico de barras de la distribución binomial.\n:::\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nprob_c_antes <- pnorm(15, mean = media, sd = desviacion)\nprob_c_despues <- 1 - pnorm(25, mean = media, sd = desviacion)\nprob_c <- prob_c_antes + prob_c_despues\ncat(\"c)\", round(prob_c, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nc) 0.4051 \n```\n\n\n:::\n:::\n\n\nLa probabilidad de que se pierda el café es de 0.4051.\n\n**Grafica**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nrango <- c(media - 3 * desviacion, media + 3 * desviacion)\nggplot(data.frame(x = rango), aes(x = x)) +\n  stat_function(fun = dnorm, args = list(mean = media, sd = desviacion), n = 500) +\n  geom_area(stat = \"function\", fun = dnorm, args = list(mean = media, sd = desviacion), fill = \"gray\", xlim = c(min(rango), 15), alpha = 0.6) +\n  geom_area(stat = \"function\", fun = dnorm, args = list(mean = media, sd = desviacion), fill = \"gray\", xlim = c(25, max(rango)), alpha = 0.6) +\n  labs(title = \"Distribucion Normal\", subtitle = \"Probabilidad de perder el café\", x = \"Tiempo de viaje (minutos)\", y = \"Densidad de Probabilidad\") +\n  geom_vline(xintercept = 15, linetype = \"dashed\", color = \"red\") +\n  geom_vline(xintercept = 25, linetype = \"dashed\", color = \"red\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](trabajoestadis_files/figure-html/unnamed-chunk-22-1.png){fig-align='center' width=70%}\n:::\n:::\n\n\nLa probabilidad de que se pierda el café es de 40.51%.\n\n#### Inciso D\n\nEncuentre la longitud de tiempo por arriba de la cual encontramos e1 15% de los viajes más lentos.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nvalor_d <- qnorm(0.85, mean = media, sd = desviacion)\ncat(\"d)\", round(valor_d, 2), \"minutos\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nd) 27.94 minutos\n```\n\n\n:::\n:::\n\n\nLa longitud de tiempo por arriba de la cual encontramos e1 15% de los viajes más lentos es 27.94 minutos.\n\n**Grafica**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmedia <- 24\ndesviacion <- 3.8\nvalor_cuantil <- qnorm(0.85, mean = media, sd = desviacion)\nrango <- c(media - 3 * desviacion, media + 3 * desviacion)\nlibrary(ggplot2)\nggplot(data.frame(x = rango), aes(x = x)) +\n  stat_function(fun = dnorm, args = list(mean = media, sd = desviacion), n = 500) +\n  geom_area(stat = \"function\", fun = dnorm, args = list(mean = media, sd = desviacion), fill = \"#11de07\", xlim = c(valor_cuantil, max(rango)), alpha = 0.6) +\n  labs(    title = \"Distribucion Normal\", subtitle = \"Viajes más lentos (15% superior)\",    x = \"Tiempo de viaje (minutos)\",    y = \"Densidad de Probabilidad\"  ) +\n  geom_vline(xintercept = valor_cuantil, linetype = \"dashed\", color = \"red\") +\n  geom_text(aes(x = valor_cuantil, y = dnorm(valor_cuantil, mean = media, sd = desviacion), label = paste0(round(valor_cuantil, 2), \" min\")), vjust = -1, hjust = -0.1) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](trabajoestadis_files/figure-html/unnamed-chunk-24-1.png){fig-align='center' width=70%}\n:::\n:::\n\n\nLa longitud de tiempo por arriba de la cual encontramos e1 15% de los viajes más lentos es 27.94 minutos.\n\n#### Inciso E\n\nEncuentre la probabilidad de que 2 de los siguientes 3 viajes tomen al menos 1/2 hora.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\np_exito <- 1 - pnorm(30, mean = media, sd = desviacion)\nn_viajes <- 3\nx_exitos <- 2\nprob_e <- dbinom(x_exitos, size = n_viajes, prob = p_exito)\ncat(\"e)\", round(prob_e, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ne) 0.0092 \n```\n\n\n:::\n:::\n\n\nLa probabilidad de que 2 de los siguientes 3 viajes tomen al menos 1/2 hora es 0.0092.\n\n**Grafica**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\np_exito <- 1 - pnorm(30, mean = 24, sd = 3.8) \nn_viajes <- 3 \nexitos_deseados <- 0:n_viajes\nprobabilidades <- dbinom(exitos_deseados, size = n_viajes, prob = p_exito)\ndf_binomial <- data.frame( num_exitos = factor(exitos_deseados),  prob = probabilidades)\nlibrary(ggplot2)\nggplot(df_binomial, aes(x = num_exitos, y = prob)) +\n  geom_bar(stat = \"identity\", fill = \"skyblue\") +\n  geom_text(aes(label = round(prob, 4)), vjust = -0.5) +\n  labs(    title = \"Distribución Binomial de viajes que tardan ≥ 30 minutos\",   subtitle = \"La probabilidad de tener exactamente 2 'éxitos' es del 0.94%\", x = \"Número de viajes de al menos 30 minutos\",   y = \"Probabilidad\"  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](trabajoestadis_files/figure-html/unnamed-chunk-26-1.png){fig-align='center' width=70%}\n:::\n:::\n\n\nLa probabilidad de que 2 de los siguientes 3 viajes tomen al menos 1/2 hora es 0.92%.\n::::\n\n<br>\n\n## Ejercicio 6.13 {.unnumbered}\n\nLa vida promedio de cierto tipo de motor pequeño es de 10 años con una desviación estándar de 2 años. El fabricante reemplaza gratis todos los motores que fallen dentro del periodo de garantía. Si él está dispuesto a reemplazar sólo 3% de los motores que fallan, ¿cuánto tiempo de garantía debería ofrecer? Suponga que la duración de un motor sigue una distribución normal.\n\n- **Parametros**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmedia <- 10       \ndesviacion <- 2    \nprobabilidad_fallo <- 0.03 \n```\n:::\n\n\n### Solución\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ntiempo_garantia <- qnorm(probabilidad_fallo, mean = media, sd = desviacion)\ncat(\"El fabricante debería ofrecer una garantía de:\", round(tiempo_garantia, 2), \"años\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nEl fabricante debería ofrecer una garantía de: 6.24 años\n```\n\n\n:::\n:::\n\n\n**Grafica**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmedia <- 10\ndesviacion <- 2\ntiempo_garantia <- qnorm(0.03, mean = media, sd = desviacion)\nrango <- c(media - 3 * desviacion, media + 3 * desviacion)\nggplot(data.frame(x = rango), aes(x = x)) +\n   stat_function(fun = dnorm, args = list(mean = media, sd = desviacion), n = 500, color = \"black\") +  \n  geom_area(stat = \"function\", fun = dnorm, args = list(mean = media, sd = desviacion),  fill = \"purple\", xlim = c(min(rango), tiempo_garantia), alpha = 0.6) + \n  labs(    title = \"Período de Garantía de los Motores\",    subtitle = \"El 3% de los motores fallará antes del período de garantía\",    x = \"Vida útil del motor (años)\",    y = \"Densidad de Probabilidad\"  ) +\n  theme_bw() +\n  geom_vline(xintercept = tiempo_garantia, linetype = \"dashed\", color = \"red\") +\n  geom_text(aes(x = tiempo_garantia, y = 0.01, label = paste0(round(tiempo_garantia, 2), \" años\")), \n            hjust = 1.1, vjust = -1)\n```\n\n::: {.cell-output-display}\n![](trabajoestadis_files/figure-html/unnamed-chunk-29-1.png){fig-align='center' width=70%}\n:::\n:::\n\n\nEl fabricante debería ofrecer una garantía de 6.24 años.\n\n------------------------------------------------------------------------\n\n## Ejercicio 6.15 {.unnumbered}\n\nUna compañía paga a sus empleados un salario promedio de \\$15.90 por hora con una desviación estándar de \\$1.50. Si los salarios se distribuyen aproximadamentede forma normal y se pagan al centavo más 6.15 Una compañía paga a sus empleados un salario promedio de \\$15.90 por hora con una desviación estándar de \\$1.50. Si los salarios se distribuyen aproximadamente de forma normal y se pagan al centavo más 6.15 Una compañía paga a sus empleados un salario promedio de \\$15.90 por hora con una desviación estándar de \\$1.50. Si los salarios se distribuyen aproximadamente de forma normal y se pagan al centavo más cercano\n\n**a)** ¿qué porcentaje de los trabajadores reciben salarios entre \\$13.75 y \\$16.22 inclusive por hora?<br>**b)** ¿el 5% más alto de los salarios por hora de los empleados es mayor a qué cantidad?\n\n- **Parametros**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmedia <- 15.90\ndesviacion <- 1.50\nlimite_inferior <- 13.75 - 0.005\nlimite_superior <- 16.22 + 0.005\n```\n:::\n\n\n### Solución a los incisos\n\n::: panel-tabset\n#### Inciso A\n\n¿Qué porcentaje de los trabajadores reciben salarios entre \\$13.75 y \\$16.22 inclusive por hora?\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nprob_a_superior <- pnorm(limite_superior, mean = media, sd = desviacion)\nprob_a_inferior <- pnorm(limite_inferior, mean = media, sd = desviacion)\nprob_a <- prob_a_superior - prob_a_inferior\nporcentaje_a <- prob_a * 100\ncat(\"a)\", round(porcentaje_a, 2), \"%\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\na) 51.04 %\n```\n\n\n:::\n:::\n\n\n**Grafica**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nrango <- c(media - 3 * desviacion, media + 3 * desviacion)\nggplot(data.frame(x = rango), aes(x = x)) +\n  stat_function(fun = dnorm, args = list(mean = media, sd = desviacion), n = 500) +\n  geom_area(stat = \"function\", fun = dnorm, args = list(mean = media, sd = desviacion), fill = \"darkgreen\", xlim = c(limite_inferior, limite_superior), alpha = 0.6) +\n  labs(    title = \"Porcentaje de salarios entre $13.75 y $16.22\",  x = \"Salario por hora ($)\", y = \"Densidad de probabilidad\"  ) +\n  geom_vline(xintercept = c(limite_inferior, limite_superior), linetype = \"dashed\", color = \"red\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](trabajoestadis_files/figure-html/unnamed-chunk-32-1.png){fig-align='center' width=70%}\n:::\n:::\n\n\nEl porcentaje de trabajadores con salarios entre \\$13.75 y \\$16.22 es 51.04 %.\n\n#### Inciso B\n\n¿El 5% más alto de los salarios por hora de los empleados es mayor a qué cantidad?\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmedia <- 15.90\ndesviacion <- 1.50\nvalor_b <- qnorm(0.95, mean = media, sd = desviacion)\ncat(\"b)\", round(valor_b, 2), \"$\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nb) 18.37 $\n```\n\n\n:::\n:::\n\n\nEl 5% más alto de los salarios es mayor a \\$18.37.\n\n**Grafica**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nrango <- c(media - 3 * desviacion, media + 3 * desviacion)\nggplot(data.frame(x = rango), aes(x = x)) +\n  stat_function(fun = dnorm, args = list(mean = media, sd = desviacion), n = 500) +\n  geom_area(stat = \"function\", fun = dnorm, args = list(mean = media, sd = desviacion), fill = \"purple\", xlim = c(valor_b, max(rango)), alpha = 0.6) +\n  labs(    title = \"El 5% de salarios más altos\",  x = \"Salario por hora ($)\", y = \"Densidad de probabilidad\" ) +\n  geom_vline(xintercept = valor_b, linetype = \"dashed\", color = \"red\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](trabajoestadis_files/figure-html/unnamed-chunk-34-1.png){fig-align='center' width=70%}\n:::\n:::\n\n\nEl 5% más alto de los salarios es mayor a \\$18.37.\n:::\n\n<br>\n\nsdlfijdios\n\n\n::: {.cell layout-align=\"center\" standalone='true'}\n\n```{.r .cell-code}\nlibrary(shiny)\n\nui <- fluidPage(\n  titlePanel(\"Ejemplo ShinyLive\"),\n  \n  sidebarLayout(\n    sidebarPanel(\n      sliderInput(\n        \"n\",\n        \"Cantidad de datos:\",\n        min = 10,\n        max = 1000,\n        value = 100\n      )\n    ),\n    \n    mainPanel(\n      plotOutput(\"hist\")\n    )\n  )\n)\n\nserver <- function(input, output) {\n  \n  output$hist <- renderPlot({\n    hist(rnorm(input$n))\n  })\n}\n\nshinyApp(ui, server)\n```\n\n::: {.cell-output-display}\n`<div style=\"width: 100% ; height: 400px ; text-align: center; box-sizing: border-box; -moz-box-sizing: border-box; -webkit-box-sizing: border-box;\" class=\"muted well\">Shiny applications not supported in static R Markdown documents</div>`{=html}\n:::\n:::\n\n",
    "supporting": [
      "trabajoestadis_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}